/**
 * Determinism property tests (Work Order A010 gate 15) — random LEGAL
 * event sequences through the lifecycle state machine and the event
 * log, generated by a seeded, in-file LCG (the package's own determinism
 * primitive; no new dependencies, no Math.random, no wall-clock sleeps).
 *
 * Invariants:
 *   P1 every randomly-walked legal path is accepted by BOTH the FSM and
 *      the event log (log adjacency + fold agree with the table);
 *   P2 the illegal sibling of every legal step is rejected with
 *      ILLEGAL_TRANSITION / EVENT_OUT_OF_ORDER (no illegal pair ever
 *      slips through);
 *   P3 full-run determinism — the same seed drives two independent
 *      builds to byte-identical canonical logs (digest comparison);
 *   P4 different seeds diverge (non-degenerate harness);
 *   P5 terminal finality holds along every path (completed/failed/
 *      timed-out accept only cleanup; cleaned accepts nothing);
 *   P6 every produced log passes strict re-verification by replay.
 */

import { describe, expect, it } from 'vitest';
import { canonicalJson, toCorrelationId, toIdempotencyKey } from '@arena/protocol-core';
import { createSeededLcg, stepLcg } from './determinism.js';
import {
  RUN_LIFECYCLE_EVENTS,
  RUN_STATES,
  RUN_TRANSITIONS,
  canTransitionRunState,
  legalRunEventsFrom,
  targetRunState,
  transitionRunState,
} from './lifecycle.js';
import type { RunLifecycleEvent, RunState } from './lifecycle.js';
import {
  appendRuntimeEventEnvelope,
  createEnvironmentEventLog,
  verifyEnvironmentEventLog,
} from './event-log.js';
import type { EnvironmentEventLog } from './event-log.js';
import { makeRuntimeEventEnvelope } from './envelopes.js';
import {
  makeAdmissionDecidedEvent,
  makeCheckpointRecordedEvent,
  makeCheckpointRestoredEvent,
  makeRunResultProducedEvent,
  makeRunSubmittedEvent,
  makeStateTransitionedEvent,
  makeWorkloadProgressedEvent,
} from './events.js';
import type { RuntimeEvent, RuntimeEventKind } from './events.js';
import { initialRunState, foldRunEvents } from './run-state.js';
import { createRunRecord } from './run-record.js';
import { nextRuntimeEventKinds } from './events.js';
import { DIGEST_C, T0, TENANT_A, makeDeclarationInput } from './test-support.js';

const SEEDS = [1, 42, 20260926, 777, 314159];
const STEP_MS_BASE = Date.parse(T0);
const IDEMPOTENCY = toIdempotencyKey('idem-property');

/** Events that may legally follow a given runtime event kind AND state. */
function nextMoves(
  lastKind: RuntimeEventKind,
  status: RunState,
  recordedCheckpoints: number,
): readonly { kind: RuntimeEventKind; event?: RunLifecycleEvent }[] {
  const moves: { kind: RuntimeEventKind; event?: RunLifecycleEvent }[] = [];
  const kinds = nextRuntimeEventKinds(lastKind);
  for (const kind of kinds) {
    if (kind === 'state-transitioned') {
      for (const event of legalRunEventsFrom(status)) moves.push({ kind, event });
    } else if (kind === 'workload-progressed' && status === 'running') {
      moves.push({ kind });
    } else if (kind === 'checkpoint-recorded' && (status === 'running' || status === 'checkpointing')) {
      moves.push({ kind });
    } else if (kind === 'checkpoint-restored' && status === 'running' && recordedCheckpoints > 0) {
      moves.push({ kind });
    } else if (kind === 'run-result-produced' && status === 'completed') {
      moves.push({ kind });
    } else if (kind === 'admission-decided' && status === 'requested') {
      moves.push({ kind });
    }
  }
  return Object.freeze(moves);
}

interface BuiltRun {
  readonly log: EnvironmentEventLog;
  readonly statuses: readonly RunState[];
}

/** Drive one seeded random LEGAL run; returns the built log + walked statuses. */
async function buildRun(seed: number): Promise<BuiltRun> {
  const rng = createSeededLcg(`property-${String(seed)}`);
  const record = await createRunRecord(
    makeDeclarationInput({ runKey: `run-${String(seed)}`, seed: `seed-${String(seed)}` }),
  );
  const base = { runId: record.runId, tenantId: record.tenantId };
  // FIXED correlation + LCG-derived UUIDv4-shaped envelope ids make the
  // whole canonical log byte-deterministic for a given seed.
  const correlation = toCorrelationId(`corr-prop-${String(seed)}`);
  const stamp = (sequence: number): string =>
    new Date(STEP_MS_BASE + sequence * 1000).toISOString();
  const enveloped = (event: RuntimeEvent) =>
    makeRuntimeEventEnvelope(event, {
      correlationId: correlation,
      idempotencyKey: IDEMPOTENCY,
      id: deterministicUuid(rng),
      issuedAt: stamp(1),
    });

  let log = createEnvironmentEventLog();
  let status: RunState = 'requested';
  let lastKind: RuntimeEventKind = 'run-submitted';
  const statuses: RunState[] = [status];
  let sequence = 1;
  let step = 0;
  let elapsed = 0;
  let checkpoints = 0;
  const worldStepAtCheckpoint = new Map<number, number>();
  let admitted = false;

  log = appendRuntimeEventEnvelope(
    log,
    enveloped(
      makeRunSubmittedEvent({
        ...base,
        sequence,
        occurredAt: stamp(sequence),
        recordDigest: record.digest,
        jobRef: record.jobRef,
        seed: record.seed,
      }),
    ),
  );

  for (let move = 0; move < 40; move += 1) {
    const moves = nextMoves(lastKind, status, checkpoints);
    if (moves.length === 0) break;
    const choice = moves[rng.int(moves.length)];
    if (choice === undefined) break;
    sequence += 1;
    const occurredAt = stamp(sequence);
    let event: RuntimeEvent;
    if (choice.kind === 'admission-decided') {
      admitted = true;
      event = makeAdmissionDecidedEvent({ ...base, sequence, occurredAt, admitted: true, violations: [] });
    } else if (choice.kind === 'state-transitioned' && choice.event !== undefined) {
      const to = transitionRunState(status, choice.event);
      event = makeStateTransitionedEvent({ ...base, sequence, occurredAt, from: status, to, lifecycleEvent: choice.event });
      status = to;
      statuses.push(status);
    } else if (choice.kind === 'workload-progressed') {
      step += 1;
      elapsed += stepLcg(record.seed ?? 'seed', 'step', step).intBetween(50, 250);
      event = makeWorkloadProgressedEvent({ ...base, sequence, occurredAt, step, simulatedElapsedMs: elapsed });
    } else if (choice.kind === 'checkpoint-recorded') {
      checkpoints += 1;
      worldStepAtCheckpoint.set(checkpoints, step);
      event = makeCheckpointRecordedEvent({
        ...base,
        sequence,
        occurredAt,
        checkpointSequence: checkpoints,
        snapshotDigest: DIGEST_C,
        stepIndex: step,
      });
    } else if (choice.kind === 'checkpoint-restored') {
      const restoreTo = Math.max(1, rng.int(checkpoints) || 1);
      const snapshotStep = worldStepAtCheckpoint.get(restoreTo) ?? 0;
      step = snapshotStep;
      event = makeCheckpointRestoredEvent({
        ...base,
        sequence,
        occurredAt,
        checkpointSequence: restoreTo,
        snapshotDigest: DIGEST_C,
        restoredStepIndex: snapshotStep,
      });
    } else {
      // run-result-produced
      event = makeRunResultProducedEvent({
        ...base,
        sequence,
        occurredAt,
        resultDigest: DIGEST_C,
        trajectoryDigest: DIGEST_C,
        evidenceDigests: [DIGEST_C],
      });
    }
    log = appendRuntimeEventEnvelope(log, enveloped(event));
    lastKind = choice.kind;
    if (status === 'cleaned') break;
    void admitted;
  }
  return { log, statuses };
}

describe('lifecycle property suite (gate 15 — seeded LCG)', () => {
  it('P1 + P6: random legal paths verify by replay; fold agrees with the table', async () => {
    for (const seed of SEEDS) {
      const { log, statuses } = await buildRun(seed);
      expect(log.entries.length).toBeGreaterThanOrEqual(3);
      verifyEnvironmentEventLog(log); // P6: strict replay verification
      // The fold over the same stream lands on the walked final status.
      const record = await createRunRecord(
        makeDeclarationInput({ runKey: `run-${String(seed)}`, seed: `seed-${String(seed)}` }),
      );
      const events = log.entries.map((envelope) => envelope.payload);
      const folded = foldRunEvents(initialRunState(record), events);
      const lastStatus = statuses[statuses.length - 1];
      if (lastStatus === undefined) throw new Error('no walked statuses');
      expect(folded.status).toBe(lastStatus);
      // P1: every walked transition was a table edge.
      for (let index = 1; index < statuses.length; index += 1) {
        const from = statuses[index - 1];
        const to = statuses[index];
        if (from === undefined || to === undefined) throw new Error('walked path gap');
        expect(RUN_TRANSITIONS.some((edge) => edge.from.includes(from) && edge.to === to)).toBe(
          true,
        );
      }
    }
  });

  it('P2: the illegal sibling of every legal step never slips through', () => {
    const rng = createSeededLcg('negative-probe');
    for (let probe = 0; probe < 200; probe += 1) {
      const from = RUN_STATES[rng.int(RUN_STATES.length)];
      const event = RUN_LIFECYCLE_EVENTS[rng.int(RUN_LIFECYCLE_EVENTS.length)];
      if (from === undefined || event === undefined) throw new Error('fixture');
      const legal = canTransitionRunState(from, event);
      if (legal) {
        expect(transitionRunState(from, event)).toBe(targetRunState(from, event));
      } else {
        expect(() => transitionRunState(from, event)).toThrow();
      }
    }
    // Exhaustive: table-legal pairs are exactly the accepted pairs.
    for (const from of RUN_STATES) {
      for (const event of RUN_LIFECYCLE_EVENTS) {
        const edge = RUN_TRANSITIONS.find(
          (candidate) => candidate.event === event && candidate.from.includes(from),
        );
        expect(canTransitionRunState(from, event)).toBe(edge !== undefined);
      }
    }
  });

  it('P3: same seed ⇒ byte-identical canonical logs', async () => {
    for (const seed of SEEDS) {
      const a = await buildRun(seed);
      const b = await buildRun(seed);
      expect(canonicalJson(b.log)).toBe(canonicalJson(a.log));
      expect(b.statuses).toEqual(a.statuses);
    }
  });

  it('P4: different seeds diverge', async () => {
    const a = await buildRun(1);
    const b = await buildRun(2);
    expect(canonicalJson(b.log)).not.toBe(canonicalJson(a.log));
  });

  it('P5: terminal finality along every path', async () => {
    for (const seed of SEEDS) {
      const { log } = await buildRun(seed);
      const kinds = log.entries.map((envelope) => envelope.payload.kind);
      // Whatever the final state, the log accepts no post-cleaned appends
      // (appendRuntimeEventEnvelope enforces it; verified by replay above).
      const lastStatus = lastTransitionedTo(log);
      if (lastStatus === 'cleaned') {
        expect(() =>
          appendRuntimeEventEnvelope(
            log,
            makeRuntimeEventEnvelope(
              makeWorkloadProgressedEvent({
                runId: 'tenant-a/run-000042',
                tenantId: TENANT_A,
                sequence: 999,
                occurredAt: '2026-01-15T10:00:00.000Z',
                step: 99,
                simulatedElapsedMs: 99,
              }),
              { correlationId: toCorrelationId('corr-post-cleaned'), idempotencyKey: IDEMPOTENCY },
            ),
          ),
        ).toThrow();
      }
      void kinds;
    }
  });

  it('deterministic workload steps: same seed + index ⇒ same duration', () => {
    for (const seed of SEEDS) {
      const first = stepLcg(`seed-${String(seed)}`, 'step', 1).intBetween(50, 250);
      const again = stepLcg(`seed-${String(seed)}`, 'step', 1).intBetween(50, 250);
      expect(again).toBe(first);
      const other = stepLcg(`seed-${String(seed)}`, 'step', 2).intBetween(50, 250);
      expect(other).not.toBe(first);
    }
  });
});

/** Deterministic UUIDv4-shaped id from the walk's own LCG (version 4, variant [89ab]). */
function deterministicUuid(rng: ReturnType<typeof createSeededLcg>): string {
  const hex = (value: number): string => value.toString(16).padStart(8, '0').slice(-8);
  const s = hex(rng.nextUint32()) + hex(rng.nextUint32()) + hex(rng.nextUint32()) + hex(rng.nextUint32());
  const version = '4';
  const variantDigit = (Number.parseInt(s.slice(16, 17), 16) & 0x3) | 0x8;
  return [
    s.slice(0, 8),
    s.slice(8, 12),
    version + s.slice(13, 16),
    variantDigit.toString(16) + s.slice(17, 20),
    s.slice(20, 32),
  ].join('-');
}

function lastTransitionedTo(log: EnvironmentEventLog): RunState | null {
  for (let index = log.entries.length - 1; index >= 0; index -= 1) {
    const entry = log.entries[index];
    if (entry !== undefined && entry.payload.kind === 'state-transitioned') {
      return entry.payload.to;
    }
  }
  return null;
}
