/**
 * Property tests (Work Order A015, gate 12 / architecture-lock rule 17) —
 * randomized definitions and lifecycles generated by a seeded, in-file LCG
 * (no new dependencies: no faker, no fast-check), mirroring
 * @arena/capability-graph's property suite pattern.
 *
 * Invariants checked on every seed:
 *   I1 digest determinism      — same random input ⇒ same definition digest;
 *      different content ⇒ different digest (no collisions across the run);
 *   I2 normalization dedup     — defaulted and explicit equivalent inputs
 *      share one digest (registry semantics);
 *   I3 legal lifecycles parse  — every record produced by a legal random op
 *      sequence passes the STRICT wire parser (parseJobRecord);
 *   I4 event contiguity        — embedded sequences are exactly 1..n and
 *      one event is appended per transition;
 *   I5 attempt bounds          — attempts never exceed maxAttempts;
 *   I6 terminal-final          — every lifecycle op on a terminal record
 *      throws JOB_TERMINAL_STATE;
 *   I7 retry math              — nextRetryAt == failAt + retryBackoffMs(...)
 *      exactly, and re-queued jobs are gated by it;
 *   I8 audit chains verify     — random audit streams always verify.
 */

import { describe, expect, it } from 'vitest';
import { toCorrelationId, toIdempotencyKey } from '@arena/protocol-core';
import {
  appendAuditRecord,
  EMPTY_AUDIT_LOG,
  verifyAuditChain,
} from './audit.js';
import {
  createJobDefinition,
  isRetryableErrorClass,
  retryBackoffMs,
} from './definition.js';
import { makeMutationAuditedEvent } from './events.js';
import {
  cancelJob,
  claimJob,
  completeJob,
  createJobRecord,
  failJob,
  parseJobRecord,
  progressJob,
  timeoutJob,
} from './record.js';
import { JOB_ERROR_CODES, JobError } from './errors.js';

// ---------------------------------------------------------------------------
// Seeded LCG (Numerical Recipes 32-bit constants) — the ONLY randomness.
// ---------------------------------------------------------------------------

class SeededLcg {
  private state: number;

  constructor(readonly seed: number) {
    // Never let the state be 0 (LCG fixed point) — scramble deterministically.
    this.state = (seed >>> 0) || 0x2f6e2b1;
  }

  nextUint32(): number {
    this.state = (Math.imul(this.state, 1664525) + 1013904223) >>> 0;
    return this.state;
  }

  /** Uniform float in [0, 1). */
  next(): number {
    return this.nextUint32() / 2 ** 32;
  }

  /** Uniform integer in [0, maxExclusive). */
  int(maxExclusive: number): number {
    return Math.floor(this.next() * maxExclusive);
  }

  pick<T>(items: readonly T[]): T {
    const picked = items[this.int(items.length)];
    if (picked === undefined) throw new Error('empty pick list');
    return picked;
  }

  bool(): boolean {
    return this.nextUint32() % 2 === 0;
  }
}

const SEEDS = [1, 42, 20260926, 777, 314159];
const CORR = toCorrelationId('corr-prop');
const IDEM = toIdempotencyKey('idem-prop');

// ---------------------------------------------------------------------------
// Random definitions
// ---------------------------------------------------------------------------

interface RandomDefinitionSpec {
  readonly input: Record<string, unknown>;
  readonly variant: number;
}

function randomDefinitionInput(rng: SeededLcg, variant: number): RandomDefinitionSpec {
  const namespaces = ['billing', 'ops', 'eval', 'learning'];
  const names = ['reconcile-ledger', 'nightly-sweep', 'grade-run', 'distill-skill'];
  const schemas = [
    'arena:schema/artifacts/material-artifact@1.0.0',
    'arena:schema/artifacts/principal@1.0.0',
    'arena:schema/protocol/envelope@1.0.0',
  ];
  const addresses = ['arena/jobs/billing', 'arena/jobs/ops', 'ops/sweep'];
  const errorClasses = ['transient', 'dependency-unavailable', 'rate-limited'];
  const priorities = ['low', 'normal', 'high', 'critical'] as const;
  const maxAttempts = 1 + rng.int(5);
  const input: Record<string, unknown> = {
    kind: {
      namespace: rng.pick(namespaces),
      name: rng.pick(names),
      version: `${1 + rng.int(3)}.${rng.int(4)}.0`,
    },
    inputSchema: rng.pick(schemas),
    correlationAddress: rng.pick(addresses),
    idempotency: {
      scope: `scope-${rng.int(50)}`,
      ...(rng.bool() ? { retentionMs: 1_000 * (1 + rng.int(100)) } : {}),
    },
    timeout: { timeoutMs: 1_000 * (1 + rng.int(60)) },
    retry: {
      maxAttempts,
      // schedule length is bounded by maxAttempts - 1 (validation rule)
      backoffScheduleMs: Array.from({ length: rng.int(maxAttempts) }, () => 100 * rng.int(50)),
      retryableErrorClasses: rng.bool() ? [rng.pick(errorClasses)] : [],
    },
    priority: rng.pick(priorities),
    ...(rng.bool()
      ? { resourceHints: { cpu: 1 + rng.int(8), memoryMb: 128 * (1 + rng.int(4)) } }
      : {}),
  };
  return { input, variant };
}

// ---------------------------------------------------------------------------
// Random lifecycles
// ---------------------------------------------------------------------------

type Op =
  | { readonly op: 'claim' }
  | { readonly op: 'progress' }
  | { readonly op: 'complete' }
  | { readonly op: 'fail' }
  | { readonly op: 'timeout' }
  | { readonly op: 'cancel' }
  | { readonly op: 'advance'; readonly ms: number };

interface LifecycleResult {
  readonly finalStatus: string;
  readonly attempts: number;
  readonly events: number;
}

async function runRandomLifecycle(
  rng: SeededLcg,
  maxAttempts: number,
  retryable: readonly string[],
  backoff: readonly number[],
): Promise<LifecycleResult> {
  const startMs = Date.parse('2026-01-15T09:30:00.000Z');
  let clockMs = startMs;
  const iso = (): string => new Date(clockMs).toISOString();

  let record = createJobRecord({
    definitionDigest: `${rng.int(16).toString(16).padStart(2, '0')}${'ab'.repeat(31)}`,
    kind: { namespace: 'ops', name: 'random-job', version: '1.0.0' },
    correlationId: CORR,
    idempotencyKey: IDEM,
    idempotencyScope: 'scope-prop',
    input: { seed: true },
    policy: {
      timeoutMs: 10_000,
      retry: { maxAttempts, backoffScheduleMs: backoff, retryableErrorClasses: retryable },
    },
    jobId: `job-prop-${rng.int(1_000_000)}`,
    submittedAt: iso(),
  });

  const errorClasses = ['transient', 'permanent', 'dependency-unavailable'];
  const ops = 40;
  for (let step = 0; step < ops; step += 1) {
    // Pick a legal op for the current state.
    const choices: Op[] = [];
    if (record.status === 'queued') choices.push({ op: 'claim' });
    if (record.status === 'running') {
      choices.push({ op: 'progress' }, { op: 'complete' }, { op: 'fail' });
      if (record.timeoutAt !== undefined && clockMs >= Date.parse(record.timeoutAt)) {
        choices.push({ op: 'timeout' });
      }
    }
    if (record.status !== 'succeeded' && record.status !== 'failed' && record.status !== 'cancelled') {
      choices.push({ op: 'cancel' }, { op: 'advance', ms: 500 * (1 + rng.int(40)) });
    }
    if (choices.length === 0) break; // terminal — nothing legal remains
    const choice = rng.pick(choices);

    switch (choice.op) {
      case 'claim': {
        // respect the backoff gate: advance past it deterministically
        if (record.nextRetryAt !== undefined && clockMs < Date.parse(record.nextRetryAt)) {
          clockMs = Date.parse(record.nextRetryAt);
        }
        const before = record.events.length;
        record = claimJob(record, { at: iso() });
        expect(record.events).toHaveLength(before + 1); // I4: one event per transition
        break;
      }
      case 'progress':
        record = progressJob(record, { at: iso(), percent: rng.int(101) });
        break;
      case 'complete':
        record = completeJob(record, { at: iso(), result: { step } });
        break;
      case 'fail': {
        const at = iso();
        const errorClass = rng.pick(errorClasses);
        const before = record.attempts;
        record = failJob(record, { at, errorClass, message: `failure-${step}` });
        // I7: retry math is exact
        if (record.status === 'queued' && record.nextRetryAt !== undefined) {
          const expectedBackoff = retryBackoffMs(
            { maxAttempts, backoffScheduleMs: backoff, retryableErrorClasses: retryable },
            before,
          );
          expect(record.nextRetryAt).toBe(
            new Date(Date.parse(at) + expectedBackoff).toISOString(),
          );
          expect(isRetryableErrorClass({ maxAttempts, backoffScheduleMs: backoff, retryableErrorClasses: retryable }, errorClass)).toBe(true);
          expect(record.attempts).toBeLessThan(maxAttempts);
        }
        break;
      }
      case 'timeout': {
        const at = iso();
        const before = record.attempts;
        record = timeoutJob(record, { at });
        if (record.status === 'queued' && record.nextRetryAt !== undefined) {
          const expectedBackoff = retryBackoffMs(
            { maxAttempts, backoffScheduleMs: backoff, retryableErrorClasses: retryable },
            before,
          );
          expect(record.nextRetryAt).toBe(
            new Date(Date.parse(at) + expectedBackoff).toISOString(),
          );
        }
        break;
      }
      case 'cancel':
        record = cancelJob(record, { at: iso(), reason: `reason-${step}` });
        break;
      case 'advance':
        clockMs += choice.ms;
        break;
    }

    // I3: every legal intermediate record passes the STRICT parser
    expect(() => parseJobRecord(JSON.parse(JSON.stringify(record)))).not.toThrow();
    // I5: attempts are bounded by the policy
    expect(record.attempts).toBeLessThanOrEqual(maxAttempts);
  }

  // I6: terminal-final — once terminal, every lifecycle op throws
  if (
    record.status === 'succeeded' ||
    record.status === 'failed' ||
    record.status === 'cancelled'
  ) {
    for (const attempt of [
      () => claimJob(record, { at: iso() }),
      () => completeJob(record, { at: iso(), result: null }),
      () => failJob(record, { at: iso(), errorClass: 'transient', message: 'x' }),
      () => timeoutJob(record, { at: iso() }),
      () => cancelJob(record, { at: iso(), reason: 'x' }),
    ]) {
      expect(attempt).toThrow(
        expect.objectContaining({ code: JOB_ERROR_CODES.TERMINAL_STATE }),
      );
    }
  }

  return {
    finalStatus: record.status,
    attempts: record.attempts,
    events: record.events.length,
  };
}

// ---------------------------------------------------------------------------
// The property suite
// ---------------------------------------------------------------------------

describe('random definition + lifecycle property tests (seeded LCG)', () => {
  it('I1 — digest determinism and distinctness across random definitions', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const digests: string[] = [];
      for (let i = 0; i < 12; i += 1) {
        const spec = randomDefinitionInput(rng, i);
        const a = await createJobDefinition(
          spec.input as unknown as Parameters<typeof createJobDefinition>[0],
        );
        const b = await createJobDefinition(
          spec.input as unknown as Parameters<typeof createJobDefinition>[0],
        );
        expect(a.digest, `seed ${seed} variant ${i}: nondeterministic digest`).toBe(b.digest);
        digests.push(a.digest);
      }
      // no collisions across distinct random inputs (w.h.p.)
      expect(new Set(digests).size, `seed ${seed}: digest collision`).toBe(digests.length);
    }
  });

  it('I2 — normalization dedup: defaulted == explicit (same digest)', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const spec = randomDefinitionInput(rng, 0);
      const defaulted = await createJobDefinition({
        kind: spec.input.kind as { namespace: string; name: string; version: string },
        inputSchema: spec.input.inputSchema as string,
        correlationAddress: spec.input.correlationAddress as string,
        idempotency: spec.input.idempotency as { scope: string; retentionMs?: number },
        timeout: spec.input.timeout as { timeoutMs: number },
        retry: spec.input.retry as {
          maxAttempts: number;
          backoffScheduleMs?: readonly number[];
          retryableErrorClasses?: readonly string[];
        },
      });
      const explicit = await createJobDefinition({
        kind: spec.input.kind as { namespace: string; name: string; version: string },
        inputSchema: spec.input.inputSchema as string,
        correlationAddress: spec.input.correlationAddress as string,
        idempotency: spec.input.idempotency as { scope: string; retentionMs?: number },
        timeout: spec.input.timeout as { timeoutMs: number },
        retry: {
          maxAttempts: (spec.input.retry as { maxAttempts: number }).maxAttempts,
          backoffScheduleMs:
            (spec.input.retry as { backoffScheduleMs?: number[] }).backoffScheduleMs ?? [],
          retryableErrorClasses:
            (spec.input.retry as { retryableErrorClasses?: string[] }).retryableErrorClasses ??
            [],
        },
        priority: 'normal',
        resourceHints: {},
      });
      expect(defaulted.digest, `seed ${seed}: normalization drift`).toBe(explicit.digest);
    }
  });

  it('I3..I7 — random legal lifecycles keep every invariant', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      for (let scenario = 0; scenario < 6; scenario += 1) {
        const maxAttempts = 1 + rng.int(4);
        const backoff = Array.from({ length: rng.int(3) }, () => 250 * (1 + rng.int(20)));
        const retryable = rng.bool() ? ['transient'] : ['transient', 'dependency-unavailable'];
        const result = await runRandomLifecycle(rng, maxAttempts, retryable, backoff);
        expect(['queued', 'running', 'succeeded', 'failed', 'cancelled']).toContain(
          result.finalStatus,
        );
        expect(result.attempts).toBeLessThanOrEqual(maxAttempts);
        expect(result.events).toBeGreaterThanOrEqual(1);
      }
    }
  });

  it('I8 — random audit streams always verify and stay deterministic', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const mutations = ['job.submit', 'job.claim', 'job.complete', 'job.fail', 'job.cancel'];
      let log = EMPTY_AUDIT_LOG;
      let ms = Date.parse('2026-01-15T09:30:00.000Z');
      for (let i = 0; i < 10; i += 1) {
        ms += 1_000 * (1 + rng.int(30));
        const event = makeMutationAuditedEvent({
          sequence: i + 1,
          occurredAt: new Date(ms).toISOString(),
          jobId: `job-${rng.int(100)}`,
          mutation: rng.pick(mutations),
          actor: { type: 'service', tenant: 'arena', principalId: 'job-orchestrator' },
          correlationId: 'corr-prop',
          envelopeId: globalThis.crypto.randomUUID(),
        });
        log = await appendAuditRecord(log, event);
      }
      await expect(verifyAuditChain(log)).resolves.toBeDefined();
      // determinism: same payloads, same digests
      const digests = log.records.map((record) => record.digest);
      expect(new Set(digests).size).toBe(digests.length);
    }
  });

  it('the LCG itself is deterministic (same seed, same stream)', () => {
    const a = new SeededLcg(7);
    const b = new SeededLcg(7);
    const streamA = Array.from({ length: 32 }, () => a.next());
    const streamB = Array.from({ length: 32 }, () => b.next());
    expect(streamA).toEqual(streamB);
    const c = new SeededLcg(8);
    expect(Array.from({ length: 8 }, () => c.next())).not.toEqual(streamA.slice(0, 8));
  });

  it('JobError carries structured codes usable by property harnesses', () => {
    const error = new JobError(JOB_ERROR_CODES.TERMINAL_STATE, { message: 'x' });
    expect(error.code).toBe('JOB_TERMINAL_STATE');
    expect(error.category).toBe('validation');
  });
});
