/**
 * Determinism property tests (Work Order A013) — random LEGAL
 * descriptor/summary combinations generated by a seeded LCG
 * (test-support's TestLcg — Numerical Recipes constants, mirroring
 * A011/A012; no new dependencies, no Math.random, no wall-clock reads).
 *
 * Invariants:
 *   P1 outcome totality — for random support summaries the derived
 *      outcome is ALWAYS exactly one of the three closed members, with
 *      the unknown cause present iff the outcome is unknown;
 *   P2 descriptor digest determinism — random legal descriptors rebuild
 *      byte-identically, and distinct parameter tuples diverge;
 *   P3 record determinism — random legal runs rebuild byte-identically
 *      (same inputs ⇒ same record digest), and shuffled support order
 *      does not change the digest (canonical ordering);
 *   P4 input-digest stability — the computed input digest is a pure
 *      function of (verifierRef, evidence) and diverges on any change;
 *   P5 adversarial totality — random TAMPERED records never verify:
 *      digest recomputation always fails closed;
 *   P6 no-numbers invariant — random legal records contain no numeric
 *      field other than recordVersion (the construction-level
 *      impossibility of quantitative outcomes).
 */

import { describe, expect, it } from 'vitest';
import { VERIFICATION_OUTCOMES } from './outcome.js';
import { deriveVerificationOutcome } from './outcome.js';
import type { EvidenceSupportSummary, RequirementSupport } from './evidence.js';
import { createVerifierDescriptor } from './descriptor.js';
import {
  computeVerificationInputDigest,
  createVerificationRecord,
  recomputeVerificationRecordDigest,
  verificationRecordView,
} from './record.js';
import { VERIFIER_METHODS } from './verifier-method.js';
import { REPRODUCIBILITY_POLICIES } from './descriptor.js';
import { TestLcg, makeArtifact, makeDescriptorInput, makeRecordInput, support } from './test-support.js';

const SEEDS = [1, 42, 20260928, 777, 314159];
const STATUSES = [
  'present-supported',
  'present-unsupported',
  'present-unverified',
  'present-indeterminate',
  'missing',
] as const;

const T0 = '2026-03-01T12:00:00.000Z';
const T1 = '2026-03-01T12:00:01.000Z';

async function randomRun(seed: number) {
  const rng = new TestLcg(seed);
  const requirementCount = 2 + rng.int(3); // 2..4 requirements
  const method = VERIFIER_METHODS[rng.int(VERIFIER_METHODS.length)] ?? 'constraint_check';
  const policy = REPRODUCIBILITY_POLICIES[rng.int(REPRODUCIBILITY_POLICIES.length)] ?? 'deterministic';
  const seedValue = policy === 'seeded-stochastic' ? `seed-${String(seed)}` : null;
  const requirements = Array.from({ length: requirementCount }, (_, index) => ({
    requirementId: `requirement-${String(index + 1).padStart(3, '0')}`,
    evidenceKind: index % 2 === 0 ? 'test-report' : 'balance-proof',
    claim: `claim ${String(index + 1)}: the evidence must support this statement`,
    artifact: null,
    requiredProducer: index % 3 === 0 ? 'erp-close-sandbox' : null,
  }));
  const descriptor = await createVerifierDescriptor(
    makeDescriptorInput({
      verifierId: `verifier-prop-${String(seed)}`,
      version: `${1 + rng.int(3)}.${rng.int(5)}.${rng.int(7)}`,
      method,
      policy,
      seed: seedValue,
      requirements,
    }),
  );
  // One artifact per distinct kind; statuses drawn at random.
  const report = await makeArtifact(100 + (seed % 7));
  const balance = await makeArtifact(200 + (seed % 7));
  const evidence = [
    { evidenceKind: 'test-report', artifact: report, producedBy: 'arena-reference-fabric' },
    { evidenceKind: 'balance-proof', artifact: balance, producedBy: 'erp-close-sandbox' },
  ].map((entry) => ({
    evidenceKind: entry.evidenceKind,
    artifact: {
      namespace: entry.artifact.identity.namespace,
      name: entry.artifact.identity.name,
      version: entry.artifact.identity.version,
      digest: entry.artifact.digest,
    },
    provenance: { producedBy: entry.producedBy, producedAt: T0, notes: null },
  }));
  const bundleDigests = { 'test-report': report.digest, 'balance-proof': balance.digest };
  const statuses = requirements.map((_requirement) => STATUSES[rng.int(STATUSES.length)]);
  const evidenceSupport = requirements.map((requirement, index) => {
    const status = statuses[index] as (typeof STATUSES)[number];
    return support(
      requirement.requirementId,
      status,
      status === 'missing' ? null : bundleDigests[requirement.evidenceKind as keyof typeof bundleDigests],
      null,
    );
  });
  return { rng, descriptor, requirements, evidence, evidenceSupport, report, balance };
}

describe('property: outcome totality under random summaries (P1)', () => {
  for (const seed of SEEDS) {
    it(`seed ${String(seed)}: every random summary yields exactly one closed outcome`, () => {
      const rng = new TestLcg(seed);
      for (let trial = 0; trial < 25; trial += 1) {
        const count = 1 + rng.int(4);
        const summary: EvidenceSupportSummary = Array.from({ length: count }, (_, index) => {
          const status = STATUSES[rng.int(STATUSES.length)] ?? 'missing';
          const entry: RequirementSupport = {
            requirementId: `req-${String(index)}` as RequirementSupport['requirementId'],
            status,
            evidenceDigest: (status === 'missing' ? null : 'a'.repeat(64)) as RequirementSupport['evidenceDigest'],
            notes: null,
          };
          return entry;
        });
        const { outcome, unknownCause } = deriveVerificationOutcome(summary);
        expect(VERIFICATION_OUTCOMES).toContain(outcome);
        expect((outcome === 'unknown') === (unknownCause !== null)).toBe(true);
        if (unknownCause !== null) {
          expect(['missing-evidence', 'unverifiable-provenance', 'method-limitation']).toContain(
            unknownCause.reason,
          );
        }
      }
    });
  }
});

describe('property: descriptor digest determinism (P2)', () => {
  for (const seed of SEEDS) {
    it(`seed ${String(seed)}: two independent builds of the same random descriptor are byte-identical`, async () => {
      const rng = new TestLcg(seed);
      const input = makeDescriptorInput({
        verifierId: `verifier-prop-${String(seed)}`,
        version: `${1 + rng.int(3)}.${rng.int(5)}.${rng.int(7)}`,
        method: VERIFIER_METHODS[rng.int(VERIFIER_METHODS.length)] ?? 'constraint_check',
        policy: 'deterministic',
        seed: null,
        requirements: [
          {
            requirementId: 'requirement-001',
            evidenceKind: 'test-report',
            claim: `random claim ${String(rng.int(1000))}`,
            artifact: null,
            requiredProducer: null,
          },
        ],
      });
      const a = await createVerifierDescriptor(input);
      const b = await createVerifierDescriptor(input);
      expect(a.digest).toBe(b.digest);
      const firstRequirement = input.requiredEvidence[0]!;
      const variant = await createVerifierDescriptor({
        ...input,
        requiredEvidence: [
          { ...firstRequirement, claim: `mutated claim ${String(rng.int(1000))}` },
        ],
      });
      expect(variant.digest).not.toBe(a.digest);
    });
  }
});

describe('property: record determinism + canonical ordering (P3)', () => {
  for (const seed of SEEDS) {
    it(`seed ${String(seed)}: same random run ⇒ identical digest; shuffled support order ⇒ same digest`, async () => {
      const { descriptor, evidence, evidenceSupport } = await randomRun(seed);
      const input = makeRecordInput(descriptor.digest, evidence, evidenceSupport, {
        startedAt: T0,
        finishedAt: T1,
      });
      const a = await createVerificationRecord(input, descriptor);
      const b = await createVerificationRecord(input, descriptor);
      expect(a.digest).toBe(b.digest);
      expect(a.outcome).toBe(b.outcome);

      const shuffled = [...evidenceSupport];
      for (let i = shuffled.length - 1; i > 0; i -= 1) {
        const rng2 = new TestLcg(seed * 31 + i);
        const j = rng2.int(i + 1);
        const tmp = shuffled[i]!;
        shuffled[i] = shuffled[j]!;
        shuffled[j] = tmp;
      }
      const reordered = await createVerificationRecord(
        makeRecordInput(descriptor.digest, evidence, shuffled, { startedAt: T0, finishedAt: T1 }),
        descriptor,
      );
      expect(reordered.digest).toBe(a.digest);
    });
  }
});

describe('property: input-digest stability (P4)', () => {
  for (const seed of SEEDS.slice(0, 3)) {
    it(`seed ${String(seed)}: input digest is pure over (verifierRef, evidence)`, async () => {
      const { descriptor, evidence } = await randomRun(seed);
      const a = await computeVerificationInputDigest(descriptor.digest, evidence as never);
      const b = await computeVerificationInputDigest(descriptor.digest, evidence as never);
      expect(a).toBe(b);
      const reorderedEvidence = [evidence[1], evidence[0]];
      const c = await computeVerificationInputDigest(descriptor.digest, reorderedEvidence as never);
      expect(c).not.toBe(a); // bundle order is committed
    });
  }
});

describe('property: adversarial tamper detection (P5)', () => {
  for (const seed of SEEDS.slice(0, 3)) {
    it(`seed ${String(seed)}: randomly mutated records NEVER verify`, async () => {
      const { descriptor, evidence, evidenceSupport } = await randomRun(seed);
      const record = await createVerificationRecord(
        makeRecordInput(descriptor.digest, evidence, evidenceSupport, { startedAt: T0, finishedAt: T1 }),
        descriptor,
      );
      const rng = new TestLcg(seed * 7 + 13);
      const mutations: Array<Record<string, unknown>> = [
        { ...record, outcome: 'pass' },
        { ...record, unknownCause: null },
        { ...record, inputDigest: 'e'.repeat(64) },
        { ...record, evidenceSupport: [...record.evidenceSupport, record.evidenceSupport[0]] },
        { ...record, startedAt: '2030-01-01T00:00:00.000Z' },
      ];
      const chosen = mutations[rng.int(mutations.length)] as unknown as typeof record;
      await expect(recomputeVerificationRecordDigest(chosen)).rejects.toThrowError();
    });
  }
});

describe('property: no-numbers invariant (P6 — lock rule 7 regression)', () => {
  for (const seed of SEEDS.slice(0, 3)) {
    it(`seed ${String(seed)}: the only number in a random record is recordVersion`, async () => {
      const { descriptor, evidence, evidenceSupport } = await randomRun(seed);
      const record = await createVerificationRecord(
        makeRecordInput(descriptor.digest, evidence, evidenceSupport, { startedAt: T0, finishedAt: T1 }),
        descriptor,
      );
      const numeric: string[] = [];
      const walk = (value: unknown, path: string): void => {
        if (typeof value === 'number') {
          numeric.push(path);
          return;
        }
        if (typeof value === 'object' && value !== null) {
          for (const [key, child] of Object.entries(value)) walk(child, `${path}.${key}`);
        }
      };
      walk(verificationRecordView(record), 'record');
      expect(numeric).toEqual(['record.recordVersion']);
    });
  }
});
