/**
 * Property tests (Work Order A004, gate 5) — random DAGs generated by a
 * seeded, in-file LCG (no new dependencies: no faker, no fast-check).
 *
 * Invariants checked on every generated graph and every insertion order:
 *   I1 order-independent digests  — same content in any append order yields
 *      the same node digests AND the same whole-graph digest;
 *   I2 idempotent reads           — repeated queries return equal results;
 *   I3 no phantom nodes           — every query result resolves in the graph;
 *   I4 acyclicity                 — constructing the DAG never throws a cycle
 *      error, and injecting a deliberate back edge ALWAYS throws
 *      CYCLE_DETECTED with the offending path;
 *   I5 content addressing         — mutating one payload field changes the
 *      node digest (different content ⇒ different digest);
 *   I6 persistence                — appendNode returns a NEW graph; the
 *      original graph's node list is unchanged (append-only);
 *   I7 closure correctness        — descendantsOf matches a naive reference
 *      transitive closure.
 */

import { describe, expect, it } from 'vitest';
import { appendEdge, appendNode, buildCapabilityGraph, capabilityGraphDigest, emptyCapabilityGraph, getNode } from './graph.js';
import type { CapabilityGraph, CapabilityGraphElement } from './graph.js';
import { createCapabilityEdge } from './edges.js';
import { createCapabilityNode } from './nodes.js';
import type { CapabilityNode } from './nodes.js';
import { capabilityNodeKey } from './identifiers.js';
import { descendantsOf, resolveNodeRef } from './queries.js';
import { CAPABILITY_GRAPH_ERROR_CODES } from './errors.js';
import { CapabilityGraphError } from './errors.js';
import type { SkillNodePayload, TitledNodePayload } from './payload.js';
import { FIXTURE_ARTIFACT_REF } from './testing.js';

// ---------------------------------------------------------------------------
// Seeded LCG (Numerical Recipes 32-bit constants) — the ONLY randomness.
// ---------------------------------------------------------------------------

class SeededLcg {
  private state: number;

  constructor(readonly seed: number) {
    // Never let the state be 0 (LCG fixed point) — scramble deterministically.
    this.state = (seed >>> 0) || 0x2f6e2b1;
  }

  nextUint32(): number {
    this.state = (Math.imul(this.state, 1664525) + 1013904223) >>> 0;
    return this.state;
  }

  /** Uniform float in [0, 1). */
  next(): number {
    return this.nextUint32() / 2 ** 32;
  }

  /** Uniform integer in [0, maxExclusive). */
  int(maxExclusive: number): number {
    return Math.floor(this.next() * maxExclusive);
  }

  pick<T>(items: readonly T[]): T {
    const picked = items[this.int(items.length)];
    if (picked === undefined) throw new Error('empty pick list');
    return picked;
  }

  bool(): boolean {
    return this.nextUint32() % 2 === 0;
  }

  /** Deterministic shuffle (Fisher-Yates over the LCG). */
  shuffle<T>(items: readonly T[]): T[] {
    const copy = [...items];
    for (let i = copy.length - 1; i > 0; i -= 1) {
      const j = this.int(i + 1);
      const a = copy[i];
      const b = copy[j];
      if (a === undefined || b === undefined) throw new Error('shuffle bounds');
      copy[i] = b;
      copy[j] = a;
    }
    return copy;
  }
}

// ---------------------------------------------------------------------------
// Random DAG generation (layered construction guarantees acyclicity)
// ---------------------------------------------------------------------------

interface RandomGraphSpec {
  readonly nodes: readonly CapabilityNode[];
  /** Edges as (source node index, target node index, kind) triples. */
  readonly edgeSpecs: readonly { source: number; target: number; kind: 'decomposes-into' | 'requires' | 'produces' }[];
}

const KIND_LAYERS = [
  ['domain'],
  ['capability', 'evaluator', 'verifier', 'expert-competency', 'observed-failure', 'tool', 'task-family', 'body-version'],
  ['sub-capability'],
  ['skill'],
] as const;

function randomTitledPayload(rng: SeededLcg, variant: number): TitledNodePayload {
  return {
    title: `node-${variant}`,
    ...(rng.bool() ? { description: `description-${variant}-${rng.int(1000)}` } : {}),
  };
}

function randomSkillPayload(rng: SeededLcg, variant: number): SkillNodePayload {
  return {
    title: `skill-${variant}`,
    summary: `summary-${variant}-${rng.int(10000)}`,
    inputs: [{ name: 'in' }],
    outputs: [{ name: 'out' }],
    prerequisites: [`prereq-${rng.int(100)}`],
    evidence: [FIXTURE_ARTIFACT_REF],
    tests: [FIXTURE_ARTIFACT_REF],
    professionalLimitations: [],
    customerData: 'none',
  };
}

async function randomGraphSpec(rng: SeededLcg): Promise<RandomGraphSpec> {
  const nodeCount = 6 + rng.int(8); // 6..13 nodes
  const nodes: CapabilityNode[] = [];
  const kinds: string[] = [];

  const layers: readonly (readonly string[])[] = KIND_LAYERS;
  for (let i = 0; i < nodeCount; i += 1) {
    // Layered kinds: early nodes are high-level, later nodes are skills.
    const layer = layers[Math.min(Math.floor((i / nodeCount) * 4), 3)] ?? ['skill'];
    const kind = rng.pick(layer);
    kinds.push(kind);
    const id = `n${i}`;
    const version = `1.${rng.int(3)}.0`;
    const node =
      kind === 'skill'
        ? await createCapabilityNode({
            kind,
            id,
            version,
            payload: randomSkillPayload(rng, i),
            provenance: { recordDigest: `${i.toString(16).padStart(2, '0')}${'ab'.repeat(31)}` },
          })
        : kind === 'observed-failure'
          ? await createCapabilityNode({
              kind,
              id,
              version,
              payload: {
                title: `failure-${i}`,
                summary: `summary-${i}`,
                observedAt: '2026-09-26T12:00:00.000Z',
                severity: rng.pick(['minor', 'moderate', 'major', 'critical'] as const),
              },
            })
          : await createCapabilityNode({
              kind,
              id,
              version,
              payload: randomTitledPayload(rng, i),
            });
    nodes.push(node);
  }

  const edgeSpecs: {
    source: number;
    target: number;
    kind: 'decomposes-into' | 'requires' | 'produces';
  }[] = [];
  // Layer-respecting decomposes-into edges (source layer < target layer by
  // node index ordering — construction guarantees a DAG).
  for (let i = 0; i < nodes.length; i += 1) {
    if (rng.next() < 0.55) {
      const target = 1 + i + rng.int(Math.max(1, nodes.length - 1 - i));
      const targetIndex = Math.min(target, nodes.length - 1);
      if (targetIndex === i) continue;
      const sourceKind = kinds[i];
      const targetKind = kinds[targetIndex];
      if (targetKind === undefined || sourceKind === undefined) continue;
      if (canDecompose(sourceKind, targetKind)) {
        edgeSpecs.push({ source: i, target: targetIndex, kind: 'decomposes-into' });
      }
    }
  }
  // requires edges among skills, only forward (i < j) — DAG-preserving.
  const skillIndexes = kinds
    .map((kind, index) => (kind === 'skill' ? index : -1))
    .filter((index) => index >= 0);
  for (let a = 0; a < skillIndexes.length; a += 1) {
    for (let b = a + 1; b < skillIndexes.length; b += 1) {
      if (rng.next() < 0.35) {
        const source = skillIndexes[a];
        const target = skillIndexes[b];
        if (source === undefined || target === undefined) continue;
        edgeSpecs.push({ source, target, kind: 'requires' });
      }
    }
  }
  return { nodes, edgeSpecs };
}

function canDecompose(sourceKind: string, targetKind: string): boolean {
  const decomposableSources = new Set(['domain', 'capability', 'sub-capability', 'skill']);
  const decomposableTargets = new Set(['capability', 'sub-capability', 'skill']);
  return decomposableSources.has(sourceKind) && decomposableTargets.has(targetKind);
}

async function buildSpec(
  spec: RandomGraphSpec,
  order: readonly number[],
  edgeOrder: readonly number[],
): Promise<CapabilityGraph> {
  const elements: CapabilityGraphElement[] = order.map((index) => {
    const node = spec.nodes[index];
    if (node === undefined) throw new Error('spec node missing');
    return node;
  });
  for (const edgeIndex of edgeOrder) {
    const edgeSpec = spec.edgeSpecs[edgeIndex];
    if (edgeSpec === undefined) continue;
    const source = spec.nodes[edgeSpec.source];
    const target = spec.nodes[edgeSpec.target];
    if (source === undefined || target === undefined) continue;
    const edge = await createCapabilityEdge({
      kind: edgeSpec.kind,
      source,
      target,
      provenance: { recordDigest: 'c0ffee'.padEnd(64, '0') },
    });
    elements.push(edge);
  }
  return buildCapabilityGraph(elements);
}

// ---------------------------------------------------------------------------
// The property suite
// ---------------------------------------------------------------------------

describe('random DAG property tests (seeded LCG, gate 5)', () => {
  const SEEDS = [1, 42, 20260926, 777, 314159];

  it('I1 — order-independent digests across insertion orders', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const spec = await randomGraphSpec(rng);
      const nodeOrder = rng.shuffle(spec.nodes.map((_, index) => index));
      const edgeOrder = rng.shuffle(spec.edgeSpecs.map((_, index) => index));
      const graphA = await buildSpec(spec, nodeOrder, edgeOrder);
      const nodeOrderB = rng.shuffle(spec.nodes.map((_, index) => index));
      const edgeOrderB = rng.shuffle(spec.edgeSpecs.map((_, index) => index));
      const graphB = await buildSpec(spec, nodeOrderB, edgeOrderB);

      // node digests are per-content: identical across orders
      const digestOf = (graph: CapabilityGraph): string[] =>
        [...graph.nodes].map((node) => node.digest).sort();
      expect(digestOf(graphA), `seed ${seed}: node digests differ by order`).toEqual(
        digestOf(graphB),
      );
      // whole-graph digest is order-independent
      expect(await capabilityGraphDigest(graphA), `seed ${seed}: graph digest differs`).toBe(
        await capabilityGraphDigest(graphB),
      );
    }
  });

  it('I2 + I3 — idempotent reads and no phantom nodes', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const spec = await randomGraphSpec(rng);
      const graph = await buildSpec(
        spec,
        spec.nodes.map((_, index) => index),
        spec.edgeSpecs.map((_, index) => index),
      );
      const domainNodes = graph.nodes.filter((node) => node.kind === 'domain');
      const queryNodes = domainNodes.length > 0 ? domainNodes : [...graph.nodes];
      for (const node of queryNodes) {
        const first = descendantsOf(graph, node);
        const second = descendantsOf(graph, node);
        expect(first, `seed ${seed}: non-idempotent read`).toEqual(second);
        for (const ref of first) {
          const resolved = resolveNodeRef(graph, ref);
          expect(resolved, `seed ${seed}: phantom node ${capabilityNodeKey(ref)}`).not.toBeNull();
          expect(getNode(graph, ref)?.digest).toBe(ref.digest);
        }
      }
    }
  });

  it('I4 — construction is cycle-free; injected back edges always throw', async () => {
    let cycleDetections = 0;
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const spec = await randomGraphSpec(rng);
      // construction itself must never throw a cycle error
      const graph = await buildSpec(
        spec,
        spec.nodes.map((_, index) => index),
        spec.edgeSpecs.map((_, index) => index),
      );
      expect(graph.edges.length).toBeGreaterThan(0);

      // inject back edges: reverse every existing hierarchical edge. A
      // reversed edge can NEVER be silently accepted: it either violates
      // the endpoint matrix at creation, or it provably closes a cycle
      // (the forward path exists), or the exact triple is already bound.
      const hierarchical = graph.edges.filter((edge) =>
        ['decomposes-into', 'requires', 'produces', 'extends-domain'].includes(edge.kind),
      );
      expect(hierarchical.length).toBeGreaterThan(0);
      for (const edge of hierarchical) {
        let caught: unknown;
        try {
          const backEdge = await createCapabilityEdge({
            kind: edge.kind,
            source: edge.target,
            target: edge.source,
            provenance: { recordDigest: 'c0ffee'.padEnd(64, '0') },
          });
          await appendEdge(graph, backEdge);
        } catch (error) {
          caught = error;
        }
        expect(caught, `seed ${seed}: reversed edge was accepted`).toBeDefined();
        const error = caught as CapabilityGraphError;
        expect(error).toBeInstanceOf(CapabilityGraphError);
        const acceptedCodes: readonly string[] = [
          CAPABILITY_GRAPH_ERROR_CODES.CYCLE_DETECTED,
          CAPABILITY_GRAPH_ERROR_CODES.IDENTITY_CONFLICT,
          CAPABILITY_GRAPH_ERROR_CODES.INVALID_EDGE,
          CAPABILITY_GRAPH_ERROR_CODES.INVALID_REF,
        ];
        expect(
          acceptedCodes.includes(error.code),
          `seed ${seed}: unexpected code ${String(error.code)}`,
        ).toBe(true);
        if (error.code === CAPABILITY_GRAPH_ERROR_CODES.CYCLE_DETECTED) {
          cycleDetections += 1;
          const path = (error.details as { path?: string[] }).path;
          expect(path?.length).toBeGreaterThanOrEqual(3);
          expect(path?.[0]).toBe(path?.[path.length - 1]);
          expect(error.message).toContain(' -> ');
        }
      }
    }
    // Reversing skill-level hierarchy (requires/produces between skills, or
    // skill decompositions) always closes a cycle; across five seeds at
    // least one reversal must have produced the cycle tripwire.
    expect(cycleDetections).toBeGreaterThan(0);
  });

  it('I5 — content addressing: one mutated payload field changes the digest', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const spec = await randomGraphSpec(rng);
      const node = spec.nodes[rng.int(spec.nodes.length)];
      if (node === undefined) throw new Error('spec node missing');
      const mutatedPayload = { ...(node.payload as unknown as Record<string, unknown>) };
      mutatedPayload['title'] = `mutated-${rng.int(1_000_000)}`;
      const mutated = await createCapabilityNode({
        kind: node.kind,
        id: node.id,
        version: node.version,
        payload: mutatedPayload,
        ...(node.provenance !== undefined ? { provenance: node.provenance } : {}),
        ...(node.supersedes !== undefined ? { supersedes: node.supersedes } : {}),
      });
      expect(mutated.digest, `seed ${seed}: digest collision on different content`).not.toBe(
        node.digest,
      );
    }
  });

  it('I6 — persistence: appendNode returns a new graph, original unchanged', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const spec = await randomGraphSpec(rng);
      const graph = await buildSpec(
        spec,
        spec.nodes.map((_, index) => index),
        spec.edgeSpecs.map((_, index) => index),
      );
      const before = graph.nodes.length;
      const extra = await createCapabilityNode({
        kind: 'tool',
        id: `extra-${seed}`,
        version: '1.0.0',
        payload: { title: 'extra' },
      });
      const next = await appendNode(graph, extra);
      expect(next).not.toBe(graph);
      expect(graph.nodes).toHaveLength(before); // original untouched (append-only)
      expect(next.nodes).toHaveLength(before + 1);
      // and the appended graph is still verifiable and frozen
      expect(Object.isFrozen(next)).toBe(true);
      await expect(
        buildCapabilityGraph([next.nodes[next.nodes.length - 1] as CapabilityNode]),
      ).resolves.toBeDefined();
    }
  });

  it('I7 — descendantsOf matches a naive reference closure', async () => {
    for (const seed of SEEDS) {
      const rng = new SeededLcg(seed);
      const spec = await randomGraphSpec(rng);
      const graph = await buildSpec(
        spec,
        spec.nodes.map((_, index) => index),
        spec.edgeSpecs.map((_, index) => index),
      );

      // Reference implementation: transitive closure over decomposes-into.
      const children = new Map<string, string[]>();
      for (const edge of graph.edges) {
        if (edge.kind !== 'decomposes-into') continue;
        const sourceKey = capabilityNodeKey(edge.source);
        const targetKey = capabilityNodeKey(edge.target);
        const list = children.get(sourceKey) ?? [];
        list.push(targetKey);
        children.set(sourceKey, list);
      }
      const referenceClosure = (startKey: string): Set<string> => {
        const seen = new Set<string>();
        const queue = [startKey];
        while (queue.length > 0) {
          const current = queue.shift();
          if (current === undefined) break;
          for (const next of children.get(current) ?? []) {
            if (seen.has(next)) continue;
            seen.add(next);
            queue.push(next);
          }
        }
        seen.delete(startKey);
        return seen;
      };

      for (const node of graph.nodes) {
        const expected = referenceClosure(capabilityNodeKey(node));
        const actual = new Set(descendantsOf(graph, node).map((ref) => capabilityNodeKey(ref)));
        expect(
          [...actual].sort(),
          `seed ${seed}: closure mismatch at ${capabilityNodeKey(node)}`,
        ).toEqual([...expected].sort());
      }
    }
  });

  it('the LCG itself is deterministic (same seed, same stream)', () => {
    const a = new SeededLcg(7);
    const b = new SeededLcg(7);
    const streamA = Array.from({ length: 32 }, () => a.next());
    const streamB = Array.from({ length: 32 }, () => b.next());
    expect(streamA).toEqual(streamB);
    const c = new SeededLcg(8);
    expect(Array.from({ length: 8 }, () => c.next())).not.toEqual(streamA.slice(0, 8));
    // shuffle respects the multiset
    const items = [1, 2, 3, 4, 5, 6, 7, 8];
    const shuffled = new SeededLcg(99).shuffle(items);
    expect([...shuffled].sort()).toEqual(items);
    // empty graph is always available and empty
    expect(emptyCapabilityGraph().nodes).toHaveLength(0);
  });
});
