/**
 * Property tests (Work Order C001) — randomized escalation requests and
 * lifecycles generated by a seeded, in-file LCG (no new dependencies: no
 * faker, no fast-check), mirroring the A015 property suite pattern.
 *
 * Invariants checked on every seed:
 *   I1 digest determinism      — identical random inputs share a digest;
 *      any single-field variation changes it;
 *   I2 legal lifecycles        — every record produced by a legal random
 *      walk over the adjacency table is wire-guard valid;
 *   I3 history contiguity      — sequences are exactly 1..n and one entry
 *      is appended per transition;
 *   I4 terminal-final          — every lifecycle op on a terminal record
 *      fails closed (typed TERMINAL_STATE);
 *   I5 verdict closure         — every denied transition carries a
 *      closed-vocabulary machine-readable reason;
 *   I6 webhook projection      — every state reached projects to a
 *      closed 13-vocabulary event (or null) and the event consumer key
 *      is unique per event id.
 */

import { describe, expect, it } from 'vitest';
import { toCorrelationId, toIdempotencyKey } from '@arena/protocol-core';
import { createEscalationRequest } from './request.js';
import {
  ESCALATION_TRANSITIONS,
  applyEscalationTransition,
  checkEscalationTransition,
  createEscalationRecord,
  isEscalationRecord,
  isTerminalEscalationState,
} from './lifecycle.js';
import { createEscalationResult } from './results.js';
import { createEscalationWebhookEvent, lifecycleEventForState } from './events.js';
import { ESCALATION_TRANSITION_REASONS } from './lifecycle.js';
import type { EscalationState } from './lifecycle.js';
import { validEscalationRequestInput } from './test-support.js';

function lcg(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1_664_525) + 1_013_904_223) >>> 0;
    return state / 0x1_0000_0000;
  };
}

const MODES = ['solve', 'correct', 'unblock', 'review', 'teach', 'tool_gap', 'knowledge', 'evaluate'] as const;
const URGENCIES = ['routine', 'priority', 'urgent', 'critical'] as const;

function pick<T>(values: readonly T[], rand: () => number): T {
  const index = Math.floor(rand() * values.length);
  const value = values[index];
  if (value === undefined) throw new Error('unreachable pick');
  return value;
}

function randomRequestInput(rand: () => number, index: number) {
  return validEscalationRequestInput({
    clientAppId: `app-${index % 7}`,
    tenantId: `tenant-${index % 5}`,
    requestId: `esc_${String(index).padStart(32, '0').slice(0, 32)}`,
    escalationModes: [pick(MODES, rand)],
    urgency: pick(URGENCIES, rand),
    deadlineInMs: 60_000 * (1 + Math.floor(rand() * 100)),
    idempotencyKey: `idem-prop-${index}`,
    correlationId: `corr-prop-${index}`,
    budget: { amountMinorUnits: Math.floor(rand() * 100_000), currency: 'USD' },
  });
}

describe('property suite — random escalations (50 seeds)', () => {
  it('I1+I2+I3+I4+I5+I6 hold on every seed', async () => {
    for (let seed = 1; seed <= 50; seed += 1) {
      const rand = lcg(seed);

      // I1 digest determinism.
      const input = randomRequestInput(rand, seed);
      const a = await createEscalationRequest(input);
      const b = await createEscalationRequest(randomRequestInput(lcg(seed), seed));
      expect(a.digest).toBe(b.digest);
      const mutated = { ...randomRequestInput(lcg(seed), seed) };
      mutated.deadlineInMs = (mutated.deadlineInMs ?? 60_000) + 1;
      const c = await createEscalationRequest(mutated);
      expect(c.digest).not.toBe(a.digest);

      // I2 legal random walk over the adjacency table.
      let record = createEscalationRecord(a, a.createdAt);
      expect(isEscalationRecord(record)).toBe(true);
      const seenStates: EscalationState[] = ['created'];
      for (let step = 0; step < 12; step += 1) {
        if (isTerminalEscalationState(record.state)) break;
        const options: readonly EscalationState[] = ESCALATION_TRANSITIONS[record.state];
        const target = pick(options, rand);
        const now = Date.parse(a.createdAt) + 1_000 * (step + 1);
        const requiresResult = target === 'submitted';
        const requiresValidation =
          target === 'result_accepted' || target === 'revision_required' || target === 'result_rejected';
        const requiresCost = target === 'paid';
        const verdict = checkEscalationTransition(record, target, {
          now,
          ...(requiresResult ? { result: createEscalationResult({ kind: 'answer', producedAt: now, summary: 's', payload: { ok: true } }) } : {}),
          ...(requiresValidation ? { validationStatus: 'passed' as const } : {}),
          ...(requiresCost
            ? {
                cost: {
                  amountMinorUnits: 1,
                  currency: 'USD',
                  arenaFeeMinorUnits: 0,
                  expertPayoutStatus: 'pending' as const,
                },
              }
            : {}),
        });
        // Every verdict reason is from the closed vocabulary (I5).
        expect(ESCALATION_TRANSITION_REASONS).toContain(verdict.reason);
        if (verdict.allowed) {
          record = applyEscalationTransition(record, target, {
            now,
            ...(requiresResult ? { result: createEscalationResult({ kind: 'answer', producedAt: now, summary: 's', payload: { ok: true } }) } : {}),
            ...(requiresValidation ? { validationStatus: 'passed' as const } : {}),
            ...(requiresCost
              ? {
                  cost: {
                    amountMinorUnits: 1,
                    currency: 'USD',
                    arenaFeeMinorUnits: 0,
                    expertPayoutStatus: 'pending' as const,
                  },
                }
              : {}),
          });
          seenStates.push(target);
          // I3 history contiguity.
          expect(record.history.length).toBe(seenStates.length);
          expect(record.history[record.history.length - 1]?.sequence).toBe(seenStates.length);
          expect(isEscalationRecord(record)).toBe(true);
        }
      }

      // I4 terminal-final.
      if (isTerminalEscalationState(record.state)) {
        expect(() =>
          applyEscalationTransition(record, 'triaged', { now: Date.parse(a.createdAt) + 1 }),
        ).toThrowError();
      }

      // I6 webhook projection of every visited state.
      for (const state of seenStates) {
        const eventType = lifecycleEventForState(state);
        if (eventType !== null) {
          const event = createEscalationWebhookEvent({
            eventType,
            request: a,
            sequence: 1,
            now: a.createdAt,
            state,
          });
          expect(event.eventId).toMatch(/^evt_[0-9a-f]{32}$/);
        }
      }
    }
  });

  it('envelope idempotency keys round trip deterministically', () => {
    const rand = lcg(1234);
    for (let i = 0; i < 25; i += 1) {
      const key = toIdempotencyKey(`idem-prop-${Math.floor(rand() * 1000)}`);
      const correlation = toCorrelationId(`corr-prop-${Math.floor(rand() * 1000)}`);
      expect(String(key)).toMatch(/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/);
      expect(String(correlation)).toMatch(/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/);
    }
  });
});
