/**
 * Determinism property tests (Work Order A015 gate 8) — random operation
 * sequences against the orchestrator, generated by a seeded, in-file LCG
 * (no new dependencies), with a deterministic envelope-id factory and a
 * ManualClock. NO wall-clock sleeps anywhere.
 *
 * Invariants:
 *   D1 full-run determinism — the same seed drives two independent runs
 *      to BYTE-IDENTICAL store state, per-job event logs and audit chain
 *      (canonical-JSON digests compared);
 *   D2 different seeds diverge (the harness is not degenerate);
 *   D3 attempts never exceed maxAttempts; events stay contiguous;
 *   D4 every produced record passes the protocol's STRICT wire parser;
 *   D5 terminal jobs are never mutated further (ops throw TERMINAL_STATE);
 *   D6 the audit chain always verifies, and every mutation is audited;
 *   D7 idempotent re-submission under random duplicate submissions returns
 *      the SAME record (no duplicate execution).
 */

import { describe, expect, it } from 'vitest';
import { canonicalJson, digestCanonical, toCorrelationId, toIdempotencyKey } from '@arena/protocol-core';
import type { CorrelationId, IdempotencyKey } from '@arena/protocol-core';
import type { CreateJobDefinitionInput, JobDefinition } from '@arena/job-protocol';
import {
  createJobDefinition,
  jobSubmissionIdentityOf,
  jobSubmissionKey,
  JobError,
  JOB_ERROR_CODES,
  parseJobRecord,
} from '@arena/job-protocol';
import { InMemoryEventSink, InMemoryJobStore, ManualClock } from './in-memory.js';
import { JobOrchestrator } from './orchestrator.js';

// ---------------------------------------------------------------------------
// Seeded LCG (Numerical Recipes 32-bit constants) — the ONLY randomness.
// ---------------------------------------------------------------------------

class SeededLcg {
  private state: number;

  constructor(readonly seed: number) {
    this.state = (seed >>> 0) || 0x2f6e2b1;
  }

  nextUint32(): number {
    this.state = (Math.imul(this.state, 1664525) + 1013904223) >>> 0;
    return this.state;
  }

  next(): number {
    return this.nextUint32() / 2 ** 32;
  }

  int(maxExclusive: number): number {
    return Math.floor(this.next() * maxExclusive);
  }

  pick<T>(items: readonly T[]): T {
    const picked = items[this.int(items.length)];
    if (picked === undefined) throw new Error('empty pick list');
    return picked;
  }

  bool(): boolean {
    return this.nextUint32() % 2 === 0;
  }
}

const START_MS = Date.parse('2026-01-15T09:30:00.000Z');
const ACTOR = { type: 'user', tenant: 'arena', principalId: 'expert-7' } as const;
const SEEDS = [1, 42, 20260926, 777, 314159];

const DEFINITION_INPUTS: CreateJobDefinitionInput[] = [
  {
    kind: { namespace: 'billing', name: 'reconcile-ledger', version: '1.2.0' },
    inputSchema: 'arena:schema/artifacts/material-artifact@1.0.0',
    correlationAddress: 'arena/jobs/billing/reconciliation',
    idempotency: { scope: 'billing-reconcile' },
    timeout: { timeoutMs: 10_000 },
    retry: {
      maxAttempts: 3,
      backoffScheduleMs: [500, 1_500],
      retryableErrorClasses: ['transient', 'timeout'],
    },
  },
  {
    kind: { namespace: 'eval', name: 'grade-run', version: '2.0.0' },
    inputSchema: 'arena:schema/artifacts/principal@1.0.0',
    correlationAddress: 'arena/jobs/eval/grading',
    idempotency: { scope: 'eval-grading' },
    timeout: { timeoutMs: 20_000 },
    retry: { maxAttempts: 2, backoffScheduleMs: [1_000] },
    priority: 'low',
  },
];

const ERROR_CLASSES = ['transient', 'permanent', 'dependency-unavailable'] as const;

interface RunResult {
  readonly storeDigest: string;
  readonly logsDigest: string;
  readonly auditDigest: string;
  readonly jobs: number;
  readonly mutations: string[];
}

/**
 * Drive one full orchestrator run from a seed: submits a random number of
 * jobs (with deliberate DUPLICATE submissions for D7), then applies a
 * random sequence of mutations, clock advances, retryDue/timeoutDue
 * sweeps, duplicate submissions and lookups.
 */
async function runScenario(seed: number): Promise<RunResult> {
  const rng = new SeededLcg(seed);
  const definitions: JobDefinition[] = [];
  for (const input of DEFINITION_INPUTS) {
    definitions.push(await createJobDefinition(input));
  }

  const clock = new ManualClock(START_MS);
  const store = new InMemoryJobStore();
  const sink = new InMemoryEventSink();
  // deterministic envelope ids: a UUID-shaped counter driven by the LCG
  let idCounter = 0;
  const newEnvelopeId = (): string => {
    idCounter += 1;
    const noise = rng.nextUint32().toString(16).padStart(8, '0').slice(0, 8);
    const noise2 = rng.nextUint32().toString(16).padStart(8, '0').slice(0, 4);
    return `${idCounter.toString(16).padStart(8, '0')}-${noise2}-4${noise.slice(0, 3)}-a${noise2.slice(0, 3)}-${noise}${noise2.slice(0, 4)}`;
  };
  const orchestrator = new JobOrchestrator({ clock, store, sink, newEnvelopeId });

  const submissions: {
    definition: JobDefinition;
    correlationId: CorrelationId;
    idempotencyKey: IdempotencyKey;
    jobId: string;
  }[] = [];

  const jobCount = 2 + rng.int(4); // 2..5 jobs
  for (let i = 0; i < jobCount; i += 1) {
    const definition = rng.pick(definitions);
    const correlationId = toCorrelationId(`corr-${rng.int(3)}`); // collisions by design
    const idempotencyKey = toIdempotencyKey(`idem-${rng.int(4)}`); // collisions by design
    const jobId = `job-${String(i).padStart(4, '0')}`;
    submissions.push({ definition, correlationId, idempotencyKey, jobId });
    await orchestrator.submit({
      definition,
      input: { n: i },
      correlationId,
      idempotencyKey,
      jobId,
      actor: ACTOR,
    });
    // deliberate duplicate submission (D7): same identity + same digest
    const duplicate = await orchestrator.submit({
      definition,
      input: { n: i },
      correlationId,
      idempotencyKey,
      jobId,
      actor: ACTOR,
    });
    const original = await store.get(jobId);
    if (original !== undefined) {
      expect(duplicate.jobId).toBe(original.jobId); // the SAME record
    }
  }

  let operations = 0;
  const steps = 60 + rng.int(40);
  for (let step = 0; step < steps; step += 1) {
    const choice = rng.next();
    if (choice < 0.14) {
      clock.advance(rng.bool() ? 2_000 : 12_000); // cross backoff/timeout boundaries
      continue;
    }
    const target = rng.pick(submissions);
    if (choice < 0.3) {
      await orchestrator.retryDue(); // pure query
      continue;
    }
    if (choice < 0.4) {
      const swept = await orchestrator.timeoutDue();
      for (const record of swept) {
        expect(['failed', 'queued']).toContain(record.status);
      }
      continue;
    }
    if (choice < 0.48) {
      // random re-submission: idempotent hit OR conflict (both legal)
      try {
        await orchestrator.submit({
          definition: target.definition,
          input: { n: -1 },
          correlationId: target.correlationId,
          idempotencyKey: target.idempotencyKey,
          jobId: `job-x-${rng.int(1000)}`,
          actor: ACTOR,
        });
      } catch (error) {
        const jobError = error as JobError;
        expect(jobError.code).toBe(JOB_ERROR_CODES.IDENTITY_CONFLICT);
      }
      continue;
    }
    if (choice < 0.56) {
      await orchestrator.get(target.jobId);
      await orchestrator.findByCorrelationId(target.correlationId);
      continue;
    }
    // lifecycle mutations — legal or throwing (terminal/transition guards)
    operations += 1;
    const mutation = rng.pick(['claim', 'progress', 'complete', 'fail', 'cancel'] as const);
    try {
      switch (mutation) {
        case 'claim':
          await orchestrator.claim({ jobId: target.jobId, actor: ACTOR });
          break;
        case 'progress':
          await orchestrator.progress({
            jobId: target.jobId,
            percent: rng.int(101),
            actor: ACTOR,
          });
          break;
        case 'complete':
          await orchestrator.complete({
            jobId: target.jobId,
            result: { step },
            actor: ACTOR,
          });
          break;
        case 'fail':
          await orchestrator.fail({
            jobId: target.jobId,
            errorClass: rng.pick(ERROR_CLASSES),
            message: `failure-${step}`,
            actor: ACTOR,
          });
          break;
        case 'cancel':
          await orchestrator.cancel({
            jobId: target.jobId,
            reason: `reason-${step}`,
            actor: ACTOR,
          });
          break;
      }
    } catch (error) {
      // only protocol guard rejections are acceptable
      const jobError = error as JobError;
      expect(
        [JOB_ERROR_CODES.TERMINAL_STATE, JOB_ERROR_CODES.INVALID_TRANSITION],
        `unexpected error: ${String(error)}`,
      ).toContain(jobError.code);
    }
  }
  expect(operations).toBeGreaterThan(0);

  // Final state: canonical digests of store records, per-job logs, audit chain
  const records = await store.list();
  const storeDigest = await digestCanonical(
    records.map((record) => JSON.parse(canonicalJson(record))),
  );
  const logsDigest = await digestCanonical(
    [...new Set(submissions.map((s) => s.jobId))].map((jobId) => {
      const log = sink.jobEventLog(jobId);
      return log === undefined
        ? { jobId, envelopes: [] }
        : {
            jobId,
            envelopes: log.envelopes.map((envelope) => JSON.parse(canonicalJson(envelope))),
          };
    }),
  );
  const auditDigest = await digestCanonical(
    sink.auditRecords().map((record) => JSON.parse(canonicalJson(record))),
  );

  // D3/D4: invariants on every record
  for (const record of records) {
    expect(record.attempts).toBeLessThanOrEqual(record.policy.retry.maxAttempts);
    expect(() => parseJobRecord(JSON.parse(JSON.stringify(record)))).not.toThrow();
    expect(record.events.map((event) => event.sequence)).toEqual(
      record.events.map((_, index) => index + 1),
    );
  }

  // D6: the audit chain verifies; every mutation kind appears
  await expect(sink.verify()).resolves.toBeUndefined();
  const mutations = sink.auditRecords().map((record) => record.payload.mutation);
  expect(mutations).toContain('job.submit');

  // D7: no two records share a submission identity (duplicates never
  // execute twice)
  const submissionKeys = records.map((record) =>
    jobSubmissionKey(jobSubmissionIdentityOf(record)),
  );
  expect(new Set(submissionKeys).size).toBe(submissionKeys.length);

  // D5: terminal jobs never revive
  for (const record of records) {
    if (
      record.status === 'succeeded' ||
      record.status === 'failed' ||
      record.status === 'cancelled'
    ) {
      await expect(
        orchestrator.claim({ jobId: record.jobId, actor: ACTOR }),
      ).rejects.toMatchObject({ code: JOB_ERROR_CODES.TERMINAL_STATE });
    }
  }

  return {
    storeDigest,
    logsDigest,
    auditDigest,
    jobs: records.length,
    mutations,
  };
}

describe('orchestrator determinism property tests (seeded LCG, gate 8)', () => {
  it('D1 — the same seed produces BYTE-IDENTICAL store, logs and audit chain', async () => {
    for (const seed of SEEDS) {
      const first = await runScenario(seed);
      const second = await runScenario(seed);
      expect(first.storeDigest, `seed ${seed}: store state diverged`).toBe(second.storeDigest);
      expect(first.logsDigest, `seed ${seed}: event logs diverged`).toBe(second.logsDigest);
      expect(first.auditDigest, `seed ${seed}: audit chain diverged`).toBe(second.auditDigest);
      expect(first.jobs).toBe(second.jobs);
      expect(first.mutations).toEqual(second.mutations);
    }
  });

  it('D2 — different seeds (generally) diverge', async () => {
    const a = await runScenario(1);
    const b = await runScenario(2);
    const diverged =
      a.storeDigest !== b.storeDigest || a.auditDigest !== b.auditDigest;
    expect(diverged).toBe(true);
  });

  it('D7 — duplicate submissions never execute twice', async () => {
    for (const seed of SEEDS) {
      // runScenario itself asserts: duplicate submissions return the SAME
      // record, and no two stored records share a submission identity.
      const result = await runScenario(seed);
      expect(result.jobs).toBeGreaterThanOrEqual(2); // 2..5 initial jobs
    }
  });

  it('the LCG itself is deterministic (same seed, same stream)', () => {
    const a = new SeededLcg(7);
    const b = new SeededLcg(7);
    expect(Array.from({ length: 16 }, () => a.next())).toEqual(
      Array.from({ length: 16 }, () => b.next()),
    );
  });
});
