/**
 * Arena design tokens (Work Order B001).
 *
 * Every visual constant of the Arena product UI lives here as a typed,
 * frozen TypeScript constant, and is projected into CSS custom properties
 * (`--arena-*`) by `generateTokensCss()`. The committed stylesheet
 * `src/tokens/tokens.css` is the generated output of that function — a test
 * fails on drift, and `pnpm --filter @arena/ui-platform tokens:css`
 * regenerates it.
 *
 * The token set is deliberately small and calm (spec/ux-architecture.md
 * UX1.0): generous whitespace, one accent, clear status colors — and one
 * visually DISTINCT treatment per product-truth state kind
 * (spec/ux-route-matrix.md UXM1.0 "State semantics" +
 * spec/product-requirements.md P1.0 "Product truth hierarchy"), so that a
 * verified fact, an evaluation score, a model output and a demo dataset can
 * never collapse into one interchangeable "AI result" badge.
 */

/** Version of the token surface (bump on breaking token changes). */
export const TOKENS_VERSION = '1.0.0';

/** A generated CSS custom property name in the Arena namespace. */
export type CssVariableName = `--arena-${string}`;

/** Token scale groups; also the CSS section order of the stylesheet. */
export const TOKEN_GROUPS = [
  'color',
  'space',
  'type',
  'font',
  'radius',
  'elevation',
  'motion',
  'breakpoint',
  'truth',
] as const;

export type TokenGroup = (typeof TOKEN_GROUPS)[number];

/** One token: a named CSS custom property with metadata. */
export interface TokenEntry {
  readonly variable: CssVariableName;
  readonly value: string;
  readonly group: TokenGroup;
  readonly description: string;
}

/**
 * The product-truth state vocabulary (UXM1.0 §State semantics, P1.0
 * §Product truth hierarchy). Exactly these ten kinds exist; "suggestion"
 * and "hypothesis" are kept as separate kinds because the route matrix
 * lists "suggestion/hypothesis" as two readings of one bullet — presenting
 * them distinctly keeps research conjectures from softening operational
 * suggestions.
 */
export const STATE_KINDS = [
  'verified',
  'evidence',
  'expert-judgment',
  'model-output',
  'simulation',
  'evaluation',
  'certification',
  'suggestion',
  'hypothesis',
  'demo',
] as const;

export type StateKind = (typeof STATE_KINDS)[number];

/** Marker glyph shapes — one per state kind, all distinct. */
export const STATE_MARKER_SHAPES = [
  'circle',
  'square',
  'diamond',
  'star',
  'triangle',
  'gauge',
  'hexagon',
  'pill',
  'ring',
  'tag',
] as const;

export type StateMarkerShape = (typeof STATE_MARKER_SHAPES)[number];

/** The visual + semantic treatment of one product-truth state kind. */
export interface StateKindConfig {
  readonly kind: StateKind;
  /** Human-facing badge label (always rendered — meaning never rests on color alone). */
  readonly label: string;
  /** Strong color: badge text and marker on the soft tint. */
  readonly color: string;
  /** Soft tint: badge background. */
  readonly softColor: string;
  /** Distinct marker shape (color-independent redundancy). */
  readonly marker: StateMarkerShape;
  /** One-line product-truth meaning, used for tooltips/teaching UI. */
  readonly meaning: string;
}

const stateKind = (
  kind: StateKind,
  label: string,
  color: string,
  softColor: string,
  marker: StateMarkerShape,
  meaning: string,
): StateKindConfig => ({ kind, label, color, softColor, marker, meaning });

/**
 * The ten product-truth treatments. Colors are hand-picked so that every
 * kind is distinguishable from every other kind by hue AND carries a unique
 * marker shape AND a unique label — three independent channels.
 */
export const STATE_KIND_CONFIGS: Readonly<Record<StateKind, StateKindConfig>> =
  Object.freeze({
    verified: stateKind(
      'verified',
      'Verified',
      '#15803d',
      '#e7f6ec',
      'circle',
      'Verified fact — confirmed by a verification step against its evidence.',
    ),
    evidence: stateKind(
      'evidence',
      'Evidence',
      '#0369a1',
      '#e3f1fa',
      'square',
      'Evidence — an artifact or observation that supports a conclusion; it is not itself the conclusion.',
    ),
    'expert-judgment': stateKind(
      'expert-judgment',
      'Expert judgment',
      '#b45309',
      '#fdf0dd',
      'diamond',
      'Expert judgment — a professional assessment by a qualified human expert.',
    ),
    'model-output': stateKind(
      'model-output',
      'Model output',
      '#6d28d9',
      '#f1e9fd',
      'star',
      'Model output — generated by a model; not verified unless independently checked.',
    ),
    simulation: stateKind(
      'simulation',
      'Simulation',
      '#0e7490',
      '#e0f4f8',
      'triangle',
      'Simulation result — produced inside a simulated environment, not a live operational fact.',
    ),
    evaluation: stateKind(
      'evaluation',
      'Evaluation',
      '#c2410c',
      '#fdeade',
      'gauge',
      'Evaluation result — scored by an evaluation suite against a declared rubric.',
    ),
    certification: stateKind(
      'certification',
      'Certification',
      '#312e81',
      '#e8e9fb',
      'hexagon',
      'Certification — applies to the tested composition and scope, never to a model alone.',
    ),
    suggestion: stateKind(
      'suggestion',
      'Suggestion',
      '#be185d',
      '#fde7f0',
      'pill',
      'Suggestion — a proposed next step; not an operational fact.',
    ),
    hypothesis: stateKind(
      'hypothesis',
      'Hypothesis',
      '#a21caf',
      '#fae6fb',
      'ring',
      'Hypothesis — a research conjecture under investigation.',
    ),
    demo: stateKind(
      'demo',
      'Demo',
      '#475569',
      '#eef1f5',
      'tag',
      'Demo — deterministic demo data; never customer-authoritative state.',
    ),
  });

/**
 * Fail-closed lookup of one state kind's treatment. Unknown kinds throw —
 * the vocabulary is closed on purpose (the UI must never invent an
 * eleventh kind of truth).
 */
export function stateKindConfig(kind: string): StateKindConfig {
  const config = (STATE_KIND_CONFIGS as Record<string, StateKindConfig | undefined>)[
    kind
  ];
  if (config === undefined) {
    throw new Error(
      `unknown product-truth state kind: ${JSON.stringify(kind)} (allowed: ${STATE_KINDS.join(', ')})`,
    );
  }
  return config;
}

// ---------------------------------------------------------------------------
// Scales
// ---------------------------------------------------------------------------

/** Neutral + brand colors (calm, light-first). */
export const COLOR = Object.freeze({
  canvas: '#f7f7f4',
  surface: '#ffffff',
  ink: '#1c2b33',
  inkMuted: '#4f6272',
  inkSubtle: '#7d8fa0',
  line: '#dde4ea',
  lineStrong: '#b9c6d1',
  primary: '#2f5d8a',
  primaryStrong: '#244a6e',
  primarySoft: '#e6eef6',
  onPrimary: '#ffffff',
  focus: '#1d3d5c',
  info: '#0369a1',
  infoSoft: '#e3f1fa',
  success: '#15803d',
  successSoft: '#e7f6ec',
  warning: '#b45309',
  warningSoft: '#fdf0dd',
  danger: '#b3261e',
  dangerSoft: '#fdeceb',
});

/** Spacing scale (rem) — generous whitespace by design. */
export const SPACE = Object.freeze({
  '2xs': '0.25rem',
  xs: '0.5rem',
  sm: '0.75rem',
  md: '1rem',
  lg: '1.5rem',
  xl: '2rem',
  '2xl': '3rem',
  '3xl': '4rem',
});

/** Type sizes (rem). */
export const TEXT = Object.freeze({
  xs: '0.75rem',
  sm: '0.875rem',
  base: '1rem',
  lg: '1.125rem',
  xl: '1.25rem',
  '2xl': '1.5rem',
  '3xl': '1.875rem',
  '4xl': '2.25rem',
});

/** Font families — platform stacks only (zero font downloads). */
export const FONT = Object.freeze({
  sans: "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  mono: "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace",
});

/** Font weights. */
export const FONT_WEIGHT = Object.freeze({
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
});

/** Line heights. */
export const LINE_HEIGHT = Object.freeze({
  tight: '1.2',
  snug: '1.35',
  normal: '1.5',
  relaxed: '1.7',
});

/** Corner radii. */
export const RADIUS = Object.freeze({
  xs: '0.25rem',
  sm: '0.375rem',
  md: '0.625rem',
  lg: '1rem',
  full: '999px',
});

/** Elevation levels. */
export const ELEVATION = Object.freeze({
  flat: 'none',
  low: '0 1px 2px rgba(28, 43, 51, 0.08), 0 1px 3px rgba(28, 43, 51, 0.06)',
  mid: '0 2px 6px rgba(28, 43, 51, 0.1), 0 1px 4px rgba(28, 43, 51, 0.06)',
  high: '0 12px 32px rgba(28, 43, 51, 0.16), 0 4px 12px rgba(28, 43, 51, 0.08)',
});

/** Motion durations — all animation respects prefers-reduced-motion. */
export const MOTION_DURATION = Object.freeze({
  none: '0ms',
  fast: '120ms',
  base: '200ms',
  slow: '320ms',
  deliberate: '480ms',
});

/** Motion easings. */
export const MOTION_EASING = Object.freeze({
  standard: 'cubic-bezier(0.2, 0, 0, 1)',
  enter: 'cubic-bezier(0, 0, 0.4, 1)',
  exit: 'cubic-bezier(0.4, 0, 1, 1)',
});

/** Responsive breakpoints (UXM1.0 §Responsive rule). */
export const BREAKPOINTS = Object.freeze({
  tablet: '768px',
  desktop: '1024px',
});

// ---------------------------------------------------------------------------
// Token registry + CSS generation
// ---------------------------------------------------------------------------

/** camelCase -> kebab-case (CSS custom properties are case-sensitive). */
function kebab(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function scale(
  group: TokenGroup,
  prefix: CssVariableName,
  values: Readonly<Record<string, string>>,
  description: string,
): TokenEntry[] {
  return Object.entries(values).map(([key, value]) => ({
    variable: `${prefix}-${kebab(key)}` as CssVariableName,
    value,
    group,
    description,
  }));
}

function truthEntries(): TokenEntry[] {
  const entries: TokenEntry[] = [];
  for (const kind of STATE_KINDS) {
    const config = stateKindConfig(kind);
    entries.push({
      variable: `--arena-truth-${kind}-color` as CssVariableName,
      value: config.color,
      group: 'truth',
      description: `${config.label} — strong color`,
    });
    entries.push({
      variable: `--arena-truth-${kind}-soft` as CssVariableName,
      value: config.softColor,
      group: 'truth',
      description: `${config.label} — soft tint`,
    });
  }
  return entries;
}

/** The complete token registry, in deterministic order. */
export const TOKEN_ENTRIES: readonly TokenEntry[] = Object.freeze([
  ...scale('color', '--arena-color', COLOR, 'Arena color token'),
  ...scale('space', '--arena-space', SPACE, 'Arena spacing token'),
  ...scale('type', '--arena-text', TEXT, 'Arena type-size token'),
  ...scale('font', '--arena-font', FONT, 'Arena font-family token'),
  ...scale('font', '--arena-font-weight', FONT_WEIGHT, 'Arena font-weight token'),
  ...scale('font', '--arena-line-height', LINE_HEIGHT, 'Arena line-height token'),
  ...scale('radius', '--arena-radius', RADIUS, 'Arena radius token'),
  ...scale('elevation', '--arena-elevation', ELEVATION, 'Arena elevation token'),
  ...scale(
    'motion',
    '--arena-motion-duration',
    MOTION_DURATION,
    'Arena motion-duration token',
  ),
  ...scale(
    'motion',
    '--arena-motion-easing',
    MOTION_EASING,
    'Arena motion-easing token',
  ),
  ...scale(
    'breakpoint',
    '--arena-breakpoint',
    BREAKPOINTS,
    'Arena responsive breakpoint token',
  ),
  ...truthEntries(),
]);

/**
 * Turn token entries into a `:root { … }` CSS custom-properties block.
 * Duplicate variable names are rejected — two tokens may never own the
 * same CSS variable.
 */
export function cssVariablesFromEntries(
  entries: readonly TokenEntry[],
): string {
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const entry of entries) {
    if (seen.has(entry.variable)) {
      throw new Error(
        `duplicate CSS variable in token registry: ${entry.variable}`,
      );
    }
    seen.add(entry.variable);
    lines.push(`  ${entry.variable}: ${entry.value};`);
  }
  return lines.join('\n');
}

/** Deterministically regenerate the full tokens stylesheet. */
export function generateTokensCss(): string {
  const groupOrder = new Map<string, number>(
    TOKEN_GROUPS.map((group, index) => [group, index]),
  );
  const sorted = [...TOKEN_ENTRIES].sort((a, b) => {
    const groupDelta =
      (groupOrder.get(a.group) ?? TOKEN_GROUPS.length) -
      (groupOrder.get(b.group) ?? TOKEN_GROUPS.length);
    if (groupDelta !== 0) return groupDelta;
    return a.variable < b.variable ? -1 : a.variable > b.variable ? 1 : 0;
  });
  return [
    '/*',
    ' * Arena design tokens — GENERATED FILE, do not edit by hand.',
    ` * Generated by @arena/ui-platform generateTokensCss() (tokens v${TOKENS_VERSION}).`,
    ' * Regenerate with: pnpm --filter @arena/ui-platform tokens:css',
    ' * Drift is caught by src/tokens/tokens.test.ts.',
    ' */',
    '',
    ':root {',
    cssVariablesFromEntries(sorted),
    '}',
    '',
  ].join('\n');
}
