/**
 * Determinism property tests (Work Order A007) — random LEGAL input
 * combinations generated by a seeded LCG (test-support's TestLcg —
 * Numerical Recipes constants, mirroring A011/A012/A013; no new
 * dependencies, no Math.random, no wall-clock reads).
 *
 * Invariants:
 *   P1 status totality — for random legal claim/policy/evidence
 *      combinations the derived status is ALWAYS exactly one of the five
 *      closed members, with the validity window present iff qualified;
 *   P2 evidence digest determinism — random legal evidence records
 *      rebuild byte-identically, and distinct inputs diverge;
 *   P3 record determinism — random legal evaluations rebuild
 *      byte-identically (same inputs ⇒ same record digest), and shuffled
 *      evidence order does not change the digest;
 *   P4 claim determinism — random legal claims rebuild byte-identically;
 *   P5 tamper totality — random TAMPERED records never verify: digest
 *      recomputation always fails closed;
 *   P6 supersession totality — the active-evidence projection is
 *      order-independent and never drops non-superseded records.
 */

import { describe, expect, it } from 'vitest';
import {
  QUALIFICATION_STATUSES,
  evaluateCompetencyClaim,
  isQualificationInForce,
  isQualificationStatus,
  recomputeQualificationRecordDigest,
} from './qualification.js';
import {
  createQualificationEvidence,
  resolveActiveEvidenceDigests,
} from './evidence.js';
import { createCompetencyClaim } from './claim.js';
import { recomputeCompetencyClaimDigest } from './claim.js';
import { createQualificationPolicy, recomputeQualificationPolicyDigest } from './policy.js';
import { TestLcg, T_FRESH, makeVerificationEvidence, makeWorkProductEvidence } from './test-support.js';

const SEEDS = [1, 42, 20260928, 777, 314159];
const EVAL_AT = '2026-01-15T09:30:00.000Z';

describe('property: qualification engine totality and determinism', () => {
  for (const seed of SEEDS) {
    it(`P1+P3: seed ${seed} — status totality, window iff qualified, byte-identical rebuild`, async () => {
      const rng = new TestLcg(seed);
      const workCount = rng.int(4); // 0..3 work products
      const staleCount = rng.int(2); // some observed stale
      const hasVerification = rng.int(2) === 1;
      const failingVerification = rng.int(4) === 0; // conflict sometimes
      const minimumCount = 1 + rng.int(2); // 1..2

      const evidence = [] as Awaited<ReturnType<typeof makeWorkProductEvidence>>[];
      for (let i = 0; i < workCount; i += 1) {
        evidence.push(
          await makeWorkProductEvidence(i + 1, {
            observedAt: i < staleCount ? '2024-12-11T09:30:00.000Z' : T_FRESH,
          }),
        );
      }
      const verification = hasVerification
        ? await makeVerificationEvidence(failingVerification ? 'fail' : 'pass')
        : undefined;

      const claim = await createCompetencyClaim({
        expertId: `expert-prop-${String(seed)}`,
        tenant: 'tenant-alpha',
        capability: {
          kind: 'skill',
          id: 'prop-skill',
          version: '1.0.0',
          digest: '7777777777777777777777777777777777777777777777777777777777777777',
        },
        proficiency: 'proficient',
        evidence: [...evidence.map((item) => item.digest), ...(verification ? [verification.digest] : [])],
        declaredAt: T_FRESH,
      });

      const policy = await createQualificationPolicy({
        policyId: 'policy-prop',
        version: '1.0.0',
        description: 'property policy',
        requirements: [
          { requirementId: 'work', evidenceKind: 'work-product-ref', minimumCount },
          ...(hasVerification
            ? [{ requirementId: 'verify', evidenceKind: 'verification-ref' as const, minimumCount: 1 }]
            : []),
        ],
        freshnessWindowDays: 30,
        validityWindowDays: 90,
        conflictEvidence: [{ evidenceKind: 'verification-ref', outcome: 'fail' }],
      });

      const allEvidence = [...evidence, ...(verification ? [verification] : [])];
      const record = await evaluateCompetencyClaim({
        claim,
        policy,
        evidence: allEvidence,
        evaluatedAt: EVAL_AT,
      });

      // P1: totality
      expect(isQualificationStatus(record.status)).toBe(true);
      expect(QUALIFICATION_STATUSES).toContain(record.status);
      if (record.status === 'qualified') {
        expect(record.validFrom).toBe(EVAL_AT);
        expect(record.validUntil).toBeDefined();
        expect(isQualificationInForce(record, EVAL_AT)).toBe(true);
      } else {
        expect(record.validFrom).toBeUndefined();
        expect(isQualificationInForce(record, EVAL_AT)).toBe(false);
      }
      // conflict evidence implies revocation (deterministic precedence)
      if (failingVerification && hasVerification) {
        expect(record.status).toBe('revoked');
      }

      // P3: byte-identical rebuild, order-independence
      const replay = await evaluateCompetencyClaim({
        claim,
        policy,
        evidence: [...allEvidence].reverse(),
        evaluatedAt: EVAL_AT,
      });
      expect(replay.digest).toBe(record.digest);
      await expect(recomputeQualificationRecordDigest(record, record.digest)).resolves.toBe(
        record.digest,
      );
    });
  }

  it('P2: random legal evidence records rebuild identically and diverge on change', async () => {
    for (const seed of SEEDS) {
      const rng = new TestLcg(seed);
      const kind = ['credential-ref', 'work-product-ref', 'verification-ref', 'evaluation-ref'][
        rng.int(4)
      ] as 'credential-ref' | 'work-product-ref' | 'verification-ref' | 'evaluation-ref';
      const build = async () =>
        createQualificationEvidence({
          kind,
          observedAt: T_FRESH,
          ...(kind === 'credential-ref'
            ? { credential: { kind: 'certification', reference: `cert-${String(seed)}` } }
            : {}),
          ...(kind === 'work-product-ref'
            ? { workProduct: { digest: '8888888888888888888888888888888888888888888888888888888888888888', description: `work ${String(seed)}` } }
            : {}),
          ...(kind === 'verification-ref'
            ? { verification: { recordDigest: '9999999999999999999999999999999999999999999999999999999999999999', outcome: 'pass' } }
            : {}),
          ...(kind === 'evaluation-ref'
            ? { evaluation: { recordDigest: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' } }
            : {}),
        });
      const a = await build();
      const b = await build();
      expect(a.digest).toBe(b.digest);
      // the same kind with different content diverges
      const different = await createQualificationEvidence({
        kind,
        observedAt: '2026-01-16T09:30:00.000Z',
        ...(kind === 'credential-ref'
          ? { credential: { kind: 'certification', reference: `cert-${String(seed)}` } }
          : {}),
        ...(kind === 'work-product-ref'
          ? { workProduct: { digest: '8888888888888888888888888888888888888888888888888888888888888888', description: `work ${String(seed)}` } }
          : {}),
        ...(kind === 'verification-ref'
          ? { verification: { recordDigest: '9999999999999999999999999999999999999999999999999999999999999999', outcome: 'pass' } }
          : {}),
        ...(kind === 'evaluation-ref'
          ? { evaluation: { recordDigest: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' } }
          : {}),
      });
      expect(different.digest).not.toBe(a.digest);
    }
  });

  it('P4: random legal claims rebuild byte-identically', async () => {
    for (const seed of SEEDS) {
      const rng = new TestLcg(seed);
      const proficiency = ['introductory', 'working', 'proficient', 'advanced', 'distinguished'][
        rng.int(5)
      ] as string;
      const build = async () =>
        createCompetencyClaim({
          expertId: `expert-${String(seed)}`,
          tenant: 'tenant-alpha',
          capability: {
            kind: 'skill',
            id: `skill-${String(seed)}`,
            version: '1.0.0',
            digest: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
          },
          proficiency,
          evidence: [
            'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
            'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
          ],
          declaredAt: T_FRESH,
        });
      const a = await build();
      const b = await build();
      expect(a.digest).toBe(b.digest);
      await expect(recomputeCompetencyClaimDigest(a, a.digest)).resolves.toBe(a.digest);
    }
  });

  it('P5: random tampered records NEVER verify (fail closed)', async () => {
    const rng = new TestLcg(20260928);
    const work1 = await makeWorkProductEvidence(1);
    const work2 = await makeWorkProductEvidence(2);
    const verification = await makeVerificationEvidence('pass');
    const claim = await createCompetencyClaim({
      expertId: 'expert-tamper',
      tenant: 'tenant-alpha',
      capability: {
        kind: 'skill',
        id: 'tamper-skill',
        version: '1.0.0',
        digest: 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
      },
      proficiency: 'proficient',
      evidence: [work1.digest, work2.digest, verification.digest],
      declaredAt: T_FRESH,
    });
    const policy = await createQualificationPolicy({
      policyId: 'policy-tamper',
      version: '1.0.0',
      description: 'tamper policy',
      requirements: [{ requirementId: 'work', evidenceKind: 'work-product-ref', minimumCount: 2 }],
      freshnessWindowDays: 30,
      validityWindowDays: 90,
      conflictEvidence: [],
    });
    const record = await evaluateCompetencyClaim({
      claim,
      policy,
      evidence: [work1, work2, verification],
      evaluatedAt: EVAL_AT,
    });
    // flip one numeric field / one string field / one list
    const mutations: Array<(r: typeof record) => typeof record> = [
      (r) => ({ ...r, satisfiedCount: 1 } as typeof record),
      (r) => ({ ...r, status: 'revoked' } as typeof record),
      (r) => ({ ...r, qualifyingEvidence: [] } as typeof record),
      (r) => ({ ...r, validUntil: '2027-01-01T00:00:00.000Z' } as typeof record),
    ];
    const mutation = mutations[rng.int(mutations.length)];
    if (mutation === undefined) throw new Error('unreachable');
    await expect(recomputeQualificationRecordDigest(mutation(record))).rejects.toThrow(
      /digest mismatch/,
    );
    // and the untampered record still verifies
    await expect(recomputeQualificationRecordDigest(record)).resolves.toBe(record.digest);
    // policies too
    await expect(recomputeQualificationPolicyDigest({ ...policy, validityWindowDays: 91 } as typeof policy)).rejects.toThrow(
      /digest mismatch/,
    );
  });

  it('P6: supersession projection is order-independent and never drops live evidence', async () => {
    for (const seed of SEEDS) {
      const rng = new TestLcg(seed);
      const records = [] as Awaited<ReturnType<typeof makeWorkProductEvidence>>[];
      for (let i = 0; i < 3; i += 1) {
        records.push(await makeWorkProductEvidence(i + 1));
      }
      // randomly supersede some records with fresh replacements
      const set: typeof records = [...records];
      for (const record of records) {
        if (rng.int(2) === 1) {
          set.push(await makeWorkProductEvidence(100 + set.length, { supersedes: record.digest }));
        }
      }
      const active = resolveActiveEvidenceDigests(set);
      const shuffled = [...set].reverse();
      expect([...resolveActiveEvidenceDigests(shuffled)]).toEqual([...active]);
      // every record not superseded within the set stays active
      const superseded = new Set(
        set.filter((r) => r.supersedes !== undefined && set.some((s) => s.digest === r.supersedes)).map((r) => r.supersedes),
      );
      for (const record of set) {
        if (!superseded.has(record.digest)) {
          expect(active).toContain(record.digest);
        }
      }
    }
  });
});
