/**
 * Determinism property tests for the reference runner (Work Order A010
 * gates 10, 15) — random legal command sequences generated by a seeded
 * LCG (the domain package's own determinism primitive; no Math.random,
 * no wall-clock sleeps).
 *
 * Invariants:
 *   D1 full-run determinism — the same seed drives two independent
 *      runner instances to byte-identical event logs (canonical-JSON
 *      digest comparison), including envelope ids;
 *   D2 the log always verifies by replay, whatever the command mix;
 *   D3 the runner never emits a workload step whose simulated duration
 *      deviates from the seeded LCG derivation for (seed, step);
 *   D4 different seeds diverge (non-degenerate harness).
 */

import { describe, expect, it } from 'vitest';
import { createEnvironmentDefinition } from '@arena/environment-protocol';
import type { EnvironmentDefinition } from '@arena/environment-protocol';
import { canonicalJson, digestCanonical, toCorrelationId, toIdempotencyKey } from '@arena/protocol-core';
import {
  SeededLcg,
  eventsForRun,
  makeAdvanceRunCommand,
  makeCheckpointRunCommand,
  makeCleanupRunCommand,
  makeCompleteRunCommand,
  makeFailRunCommand,
  makeStartRunCommand,
  makeSubmitRunCommand,
  stepLcg,
  verifyEnvironmentEventLog,
} from '@arena/environment-runtime';
import { EnvironmentRunner } from './runner.js';
import {
  InMemoryEnvironmentRegistry,
  InMemoryEventSink,
  InMemoryRunRecordStore,
  ManualClock,
} from './in-memory.js';

const DIGEST_A = 'a'.repeat(64);
const DIGEST_B = 'b'.repeat(64);
const START_MS = Date.parse('2026-01-15T09:30:00.000Z');
const SEEDS = [7, 42, 20260926, 90210];

async function definitionWithWallClock(wallClockSeconds: number): Promise<EnvironmentDefinition> {
  return createEnvironmentDefinition({
    identity: { namespace: 'tenant-a', name: 'engineering-sandbox' },
    version: '1.2.0',
    image: { imageKind: 'content-addressed-image', digest: DIGEST_A, buildDigest: null },
    initialState: {
      snapshot: { snapshotId: 'snapshot-initial', digest: DIGEST_B },
      snapshotSupport: 'supported',
    },
    seedPolicy: {
      reproducibility: {
        mode: 'nondeterministic',
        capture: {
          seed: 'the run seed drives the LCG step derivation',
          versions: 'environment-runtime 1.0.0',
          externalInputs: 'none - the reference simulation is closed',
          timingContext: 'injected manual clock',
        },
      },
      seed: 'seed-x',
      seedAlgorithm: 'lcg-32',
      reseedPolicy: 'forbidden',
    },
    actionSurface: { actions: [{ actionId: 'compile' }] },
    observationSurface: { observations: [{ observationId: 'build-log', channel: 'stdout' }] },
    resourceLimits: { cpuMillis: 4000, memoryMiB: 1024, wallClockSeconds },
    networkPolicy: {
      egress: 'default-deny',
      allows: [{ host: 'packages.example.org', port: 443, protocol: 'https' }],
    },
    filesystemPolicy: {
      writeMode: 'declared-mounts-only',
      mounts: [{ mountPath: '/workspace', access: 'read-write', source: 'workspace' }],
    },
    secretPolicy: { isolation: 'isolation-boundary', injectionPoints: [] },
    timeLimits: {
      startupSeconds: Math.min(10, wallClockSeconds),
      cleanupGraceSeconds: Math.min(5, wallClockSeconds),
      deadlineBehavior: 'hard-stop',
    },
    resetSemantics: { mode: 'recreate', checkpoint: null, cleanup: 'retain-evidence' },
    checkpointSemantics: { supported: true, triggers: ['manual'], retention: 10 },
    evidenceOutputs: {
      outputs: [
        {
          outputId: 'trajectory',
          kind: 'trajectory',
          addressing: 'content-addressed',
          description: 'the run event stream',
        },
      ],
    },
    evaluationHooks: {
      evaluators: [
        {
          hookId: 'evaluator-trajectory',
          role: 'evaluator',
          phase: 'post-run',
          invocationSchema: 'arena:schema/environment-runtime/run-result@1.0.0',
        },
      ],
      verifiers: [
        {
          hookId: 'verifier-evidence',
          role: 'verifier',
          phase: 'on-evidence',
          invocationSchema: 'arena:schema/environment-runtime/run-result@1.0.0',
        },
      ],
    },
  });
}

/** Deterministic UUIDv4-shaped envelope ids from a seeded LCG. */
function lcgEnvelopeIds(seed: number): () => string {
  const rng = new SeededLcg(seed);
  return () => {
    const hex = (n: number): string => n.toString(16).padStart(8, '0').slice(-8);
    const s =
      hex(rng.nextUint32()) + hex(rng.nextUint32()) + hex(rng.nextUint32()) + hex(rng.nextUint32());
    const variant = (Number.parseInt(s.slice(16, 17), 16) & 0x3) | 0x8;
    return [
      s.slice(0, 8),
      s.slice(8, 12),
      '4' + s.slice(13, 16),
      variant.toString(16) + s.slice(17, 20),
      s.slice(20, 32),
    ].join('-');
  };
}

interface DriveResult {
  readonly logDigest: string;
  readonly finalStatus: string;
  readonly stepDurations: readonly number[];
}

/** Drive one seeded random command mix against a fresh runner. */
async function driveRun(seed: number, wallClockSeconds: number): Promise<DriveResult> {
  const rng = new SeededLcg(seed);
  const definition = await definitionWithWallClock(wallClockSeconds);
  const clock = new ManualClock(START_MS + seed);
  const runner = new EnvironmentRunner({
    clock,
    environments: new InMemoryEnvironmentRegistry(),
    records: new InMemoryRunRecordStore(),
    sink: new InMemoryEventSink(),
    newEnvelopeId: lcgEnvelopeIds(seed),
  });
  await runner.registerEnvironment(definition);

  const runKey = `run-${String(seed)}`;
  const seedString = `seed-${String(seed)}`;
  const correlation = toCorrelationId(`corr-prop-${String(seed)}`);
  const ctx = () => ({
    correlationId: correlation,
    idempotencyKey: toIdempotencyKey(`prop-${String(seed)}`),
  });
  const target = { runId: `tenant-a/${runKey}`, tenantId: 'tenant-a' };

  await runner.submitRun(
    makeSubmitRunCommand(
      {
        declaration: {
          runKey,
          tenantId: 'tenant-a',
          environment: {
            namespace: 'tenant-a',
            name: 'engineering-sandbox',
            version: '1.2.0',
            digest: definition.digest,
          },
          jobRef: 'job-prop',
          taskVersion: { taskId: 'task-prop', version: '1.0.0' },
          initialSnapshotDigest: DIGEST_B,
          seed: seedString,
          resourceEnvelope: {
            cpuMillis: 1000,
            memoryMiB: 256,
            wallClockSeconds: Math.max(1, wallClockSeconds - 5),
          },
          networkEnvelope: {
            egress: 'default-deny',
            allows: [{ host: 'packages.example.org', port: 443, protocol: 'https' }],
          },
          filesystemEnvelope: {
            writeMode: 'declared-mounts-only',
            mounts: [{ mountPath: '/workspace', access: 'read-write', source: 'workspace' }],
          },
          secretEnvelope: { isolation: 'isolation-boundary' },
        },
      },
      ctx(),
    ),
  );
  await runner.startRun(makeStartRunCommand(target, ctx()));

  let finished = false;
  for (let move = 0; move < 25 && !finished; move += 1) {
    clock.advance(rng.intBetween(0, 2000));
    const choice = rng.int(5);
    try {
      if (choice === 0) {
        await runner.checkpointRun(makeCheckpointRunCommand(target, ctx()));
      } else if (choice === 1) {
        await runner.failRun(
          makeFailRunCommand(
            { ...target, errorClass: 'workload-error', message: 'deterministic failure' },
            ctx(),
          ),
        );
        finished = true;
      } else if (choice === 2) {
        await runner.completeRun(makeCompleteRunCommand(target, ctx()));
        finished = true;
      } else {
        await runner.advanceRun(makeAdvanceRunCommand(target, ctx()));
      }
    } catch {
      // Illegal-by-mix commands (e.g. complete after timeout) are fine:
      // the mix is random; the runner must simply reject them.
    }
  }
  // Always attempt a cleanup (no-op when the run is not terminal).
  try {
    await runner.cleanupRun(makeCleanupRunCommand(target, ctx()));
  } catch {
    /* not terminal yet — fine */
  }

  const log = await runner.eventLog();
  verifyEnvironmentEventLog(log); // D2: every mix verifies by replay
  const { state } = await runner.getRun(target.runId, 'tenant-a');
  const progressed = eventsForRun(log, target.runId)
    .map((envelope) => envelope.payload)
    .filter((event): event is Extract<typeof event, { kind: 'workload-progressed' }> => event.kind === 'workload-progressed');
  const stepDurations = progressed.map((event, index) => event.simulatedElapsedMs - (progressed[index - 1]?.simulatedElapsedMs ?? 0));
  return {
    // Byte-level: the FULL canonical log (envelope ids, issuedAt from
    // the manual clock, correlation ids — everything is deterministic).
    logDigest: await digestCanonical(JSON.parse(canonicalJson(log)) as unknown),
    finalStatus: state.status,
    stepDurations,
  };
}

describe('reference runner determinism (gates 10, 15)', () => {
  it('D1: same seed ⇒ byte-identical full logs (envelopes, ids, steps)', async () => {
    for (const seed of SEEDS) {
      const a = await driveRun(seed, 30);
      const b = await driveRun(seed, 30);
      expect(b.logDigest).toBe(a.logDigest);
      expect(b.finalStatus).toBe(a.finalStatus);
      expect(b.stepDurations).toEqual(a.stepDurations);
    }
  });

  it('D3: every emitted step duration equals the seeded LCG derivation', async () => {
    for (const seed of SEEDS) {
      const result = await driveRun(seed, 30);
      result.stepDurations.forEach((duration, index) => {
        expect(duration).toBe(
          stepLcg(`seed-${String(seed)}`, 'step', index + 1).intBetween(50, 500),
        );
      });
    }
  });

  it('D4: different seeds diverge', async () => {
    const a = await driveRun(1, 30);
    const b = await driveRun(2, 30);
    expect(b.logDigest).not.toBe(a.logDigest);
  });

  it('timeout paths verify too (wall clock exhaustion under random mixes)', async () => {
    for (const seed of SEEDS.slice(0, 2)) {
      const result = await driveRun(seed, 2); // 2s wall clock — exhausts fast
      expect(['timed-out', 'failed', 'completed', 'cleaned', 'running']).toContain(
        result.finalStatus,
      );
    }
  });
});
